#include "../pdu.h"
#include "s1ap_dict.h"

pdu_field_dict_t s1ap_fields[] = {

        { .name = "s1ap.transportLayerAddressIPv4", .desc = "transportLayerAddress(IPv4)" } ,
        { .name = "s1ap.transportLayerAddressIPv6", .desc = "transportLayerAddress(IPv6)" } ,
        { .name = "s1ap.Bearers_SubjectToStatusTransfer_Item" } ,
        { .name = "s1ap.BroadcastCancelledAreaList" } ,
        { .name = "s1ap.BroadcastCompletedAreaList" } ,
        { .name = "s1ap.Cause" } ,
        { .name = "s1ap.CellAccessMode" },
        { .name = "s1ap.Cdma2000PDU" },
        { .name = "s1ap.Cdma2000RATType" },
        { .name = "s1ap.Cdma2000SectorID" },
        { .name = "s1ap.Cdma2000HOStatus" },
        { .name = "s1ap.Cdma2000HORequiredIndication" },
        { .name = "s1ap.Cdma2000OneXSRVCCInfo" },
        { .name = "s1ap.Cdma2000OneXRAND" },
        { .name = "s1ap.CNDomain" },
        { .name = "s1ap.ConcurrentWarningMessageIndicator" },
        { .name = "s1ap.Correlation_ID" },
        { .name = "s1ap.CSFallbackIndicator" },
        { .name = "s1ap.CSG_Id" },
        { .name = "s1ap.CSG_IdList" },
        { .name = "s1ap.CSGMembershipStatus" },
        { .name = "s1ap.CriticalityDiagnostics" },
        { .name = "s1ap.DataCodingScheme" },
        { .name = "s1ap.Direct_Forwarding_Path_Availability" },
        { .name = "s1ap.Data_Forwarding_Not_Possible" },
        { .name = "s1ap.Global_ENB_ID" },
        { .name = "s1ap.GUMMEIList" },
        { .name = "s1ap.ENB_StatusTransfer_TransparentContainer" },
        { .name = "s1ap.ENB_UE_S1AP_ID" },
        { .name = "s1ap.ENBname" },
        { .name = "s1ap.E_RABInformationListItem" },
        { .name = "s1ap.E_RABList" },
        { .name = "s1ap.E_RABItem" },
        { .name = "s1ap.EUTRAN_CGI" },
        { .name = "s1ap.EUTRANRoundTripDelayEstimationInfo" },
        { .name = "s1ap.ExtendedRepetitionPeriod" },
        { .name = "s1ap.GUMMEI" },
        { .name = "s1ap.GWContextReleaseIndication" },
        { .name = "s1ap.HandoverRestrictionList" },
        { .name = "s1ap.HandoverType" },
        { .name = "s1ap.LAI" },
        { .name = "s1ap.LPPa_PDU" },
        { .name = "s1ap.MDT_Configuration" },
        { .name = "s1ap.ManagementBasedMDTAllowed" },
        { .name = "s1ap.MessageIdentifier" },
        { .name = "s1ap.MMEname" },
        { .name = "s1ap.MMERelaySupportIndicator" },
        { .name = "s1ap.MME_UE_S1AP_ID" },
        { .name = "s1ap.MSClassmark2" },
        { .name = "s1ap.MSClassmark3" },
        { .name = "s1ap.NAS_PDU" },
        { .name = "s1ap.NASSecurityParametersfromE_UTRAN" },
        { .name = "s1ap.NASSecurityParameterstoE_UTRAN" },
        { .name = "s1ap.NumberofBroadcastRequest" },
        { .name = "s1ap.OverloadResponse" },
        { .name = "s1ap.PagingDRX" },
        { .name = "s1ap.PagingPriority" },
        { .name = "s1ap.PS_ServiceNotAvailable" },
        { .name = "s1ap.RelativeMMECapacity" },
        { .name = "s1ap.RelayNode_Indicator" },
        { .name = "s1ap.RequestType" },
        { .name = "s1ap.RepetitionPeriod" },
        { .name = "s1ap.RRC_Establishment_Cause" },
        { .name = "s1ap.Routing_ID" },
        { .name = "s1ap.SecurityKey" },
        { .name = "s1ap.SecurityContext" },
        { .name = "s1ap.SerialNumber" },
        { .name = "s1ap.SONConfigurationTransfer" },
        { .name = "s1ap.Source_ToTarget_TransparentContainer" },
        { .name = "s1ap.SRVCCOperationPossible" },
        { .name = "s1ap.SRVCCHOIndication" },
        { .name = "s1ap.SourceeNB_ToTargeteNB_TransparentContainer" },
        { .name = "s1ap.ServedGUMMEIs" },
        { .name = "s1ap.ServedPLMNs" },
        { .name = "s1ap.SubscriberProfileIDforRFP" },
        { .name = "s1ap.SupportedTAs" },
        { .name = "s1ap.TimeSynchronizationInfo" },
        { .name = "s1ap.S_TMSI" },
        { .name = "s1ap.TAI" },

        { .name = "s1ap.TargetID" },
        { .name = "s1ap.TargeteNB_ToSourceeNB_TransparentContainer" },
        { .name = "s1ap.Target_ToSource_TransparentContainer" },
        { .name = "s1ap.TimeToWait" },
        { .name = "s1ap.TransportLayerAddress" },
        { .name = "s1ap.TraceActivation" },
        { .name = "s1ap.TrafficLoadReductionIndication" },
        { .name = "s1ap.UEAggregateMaximumBitrate" },
        { .name = "s1ap.UE_S1AP_IDs" },
        { .name = "s1ap.UE_associatedLogicalS1_ConnectionItem" },
        { .name = "s1ap.UEIdentityIndexValue" },
        { .name = "s1ap.UEPagingID" },
        { .name = "s1ap.UERadioCapability" },
        { .name = "s1ap.UESecurityCapabilities" },
        { .name = "s1ap.WarningAreaList" },
        { .name = "s1ap.WarningType" },
        { .name = "s1ap.WarningSecurityInfo" },
        { .name = "s1ap.WarningMessageContents" },
        { .name = "s1ap.X2TNLConfigurationInfo" },
        { .name = "s1ap.ENBX2ExtTLAs" },
        { .name = "s1ap.HandoverRequired" },
        { .name = "s1ap.HandoverCommand" },
        { .name = "s1ap.E_RABSubjecttoDataForwardingList" },
        { .name = "s1ap.E_RABDataForwardingItem" },
        { .name = "s1ap.HandoverPreparationFailure" },
        { .name = "s1ap.HandoverRequest" },
        { .name = "s1ap.E_RABToBeSetupListHOReq" },
        { .name = "s1ap.E_RABToBeSetupItemHOReq" },
        { .name = "s1ap.HandoverRequestAcknowledge" },
        { .name = "s1ap.E_RABAdmittedList" },
        { .name = "s1ap.E_RABAdmittedItem" },
        { .name = "s1ap.E_RABFailedtoSetupListHOReqAck" },
        { .name = "s1ap.E_RABFailedToSetupItemHOReqAck" },

        { .name = "s1ap.HandoverFailure" },
        { .name = "s1ap.HandoverNotify" },
        { .name = "s1ap.PathSwitchRequest" },
        { .name = "s1ap.E_RABToBeSwitchedDLList" },
        { .name = "s1ap.E_RABToBeSwitchedDLItem" },
        { .name = "s1ap.PathSwitchRequestAcknowledge" },
        { .name = "s1ap.E_RABToBeSwitchedULList" },
        { .name = "s1ap.E_RABToBeSwitchedULItem" },
        { .name = "s1ap.PathSwitchRequestFailure" },
        { .name = "s1ap.HandoverCancel" },
        { .name = "s1ap.HandoverCancelAcknowledge" },
        { .name = "s1ap.E_RABSetupRequest" },
        { .name = "s1ap.E_RABToBeSetupListBearerSUReq" },
        { .name = "s1ap.E_RABToBeSetupItemBearerSUReq" },
        { .name = "s1ap.E_RABSetupResponse" },
        { .name = "s1ap.E_RABSetupListBearerSURes" },
        { .name = "s1ap.E_RABSetupItemBearerSURes" },
        { .name = "s1ap.E_RABModifyRequest" },
        { .name = "s1ap.E_RABToBeModifiedListBearerModReq" },
        { .name = "s1ap.E_RABToBeModifiedItemBearerModReq" },
        { .name = "s1ap.E_RABModifyResponse" },
        { .name = "s1ap.E_RABModifyListBearerModRes" },
        { .name = "s1ap.E_RABModifyItemBearerModRes" },
        { .name = "s1ap.E_RABReleaseCommand" },
        { .name = "s1ap.E_RABReleaseResponse" },
        { .name = "s1ap.E_RABReleaseListBearerRelComp" },
        { .name = "s1ap.E_RABReleaseItemBearerRelComp" },
        { .name = "s1ap.E_RABReleaseIndication" },
        { .name = "s1ap.InitialContextSetupRequest" },
        { .name = "s1ap.E_RABToBeSetupListCtxtSUReq" },
        { .name = "s1ap.E_RABToBeSetupItemCtxtSUReq" },
        { .name = "s1ap.InitialContextSetupResponse" },
        { .name = "s1ap.E_RABSetupListCtxtSURes" },
        { .name = "s1ap.E_RABSetupItemCtxtSURes" },
        { .name = "s1ap.InitialContextSetupFailure" },
        { .name = "s1ap.Paging" },
        { .name = "s1ap.TAIList" },
        { .name = "s1ap.TAIItem" },


        { .name = "s1ap.UEContextReleaseRequest" },
        { .name = "s1ap.UEContextReleaseCommand" },
        { .name = "s1ap.UEContextReleaseComplete" },
        { .name = "s1ap.UEContextModificationRequest" },
        { .name = "s1ap.UEContextModificationResponse" },
        { .name = "s1ap.UEContextModificationFailure" },
        { .name = "s1ap.DownlinkNASTransport" },
        { .name = "s1ap.InitialUEMessage" },
        { .name = "s1ap.UplinkNASTransport" },
        { .name = "s1ap.NASNonDeliveryIndication" },
        { .name = "s1ap.Reset" },
        { .name = "s1ap.ResetType" },
        { .name = "s1ap.ResetAcknowledge" },
        { .name = "s1ap.UE_associatedLogicalS1_ConnectionListResAck" },
        { .name = "s1ap.ErrorIndication" },
        { .name = "s1ap.S1SetupRequest" },
        { .name = "s1ap.S1SetupResponse" },
        { .name = "s1ap.S1SetupFailure" },
        { .name = "s1ap.ENBConfigurationUpdate" },
        { .name = "s1ap.ENBConfigurationUpdateAcknowledge" },
        { .name = "s1ap.ENBConfigurationUpdateFailure" },
        { .name = "s1ap.MMEConfigurationUpdate" },
        { .name = "s1ap.MMEConfigurationUpdateAcknowledge" },
        { .name = "s1ap.MMEConfigurationUpdateFailure" },
        { .name = "s1ap.DownlinkS1cdma2000tunneling" },
        { .name = "s1ap.UplinkS1cdma2000tunneling" },
        { .name = "s1ap.UECapabilityInfoIndication" },
        { .name = "s1ap.ENBStatusTransfer" },
        { .name = "s1ap.MMEStatusTransfer" },
        { .name = "s1ap.TraceStart" },
        { .name = "s1ap.TraceFailureIndication" },
        { .name = "s1ap.DeactivateTrace" },
        { .name = "s1ap.CellTrafficTrace" },
        { .name = "s1ap.LocationReportingControl" },
        { .name = "s1ap.LocationReportingFailureIndication" },
        { .name = "s1ap.LocationReport" },
        { .name = "s1ap.OverloadStart" },
        { .name = "s1ap.OverloadStop" },
        { .name = "s1ap.WriteReplaceWarningRequest" },
        { .name = "s1ap.WriteReplaceWarningResponse" },
        { .name = "s1ap.ENBDirectInformationTransfer" },
        { .name = "s1ap.Inter_SystemInformationTransferType" },
        { .name = "s1ap.MMEDirectInformationTransfer" },
        { .name = "s1ap.ENBConfigurationTransfer" },
        { .name = "s1ap.MMEConfigurationTransfer" },
        { .name = "s1ap.PrivateMessage" },
        { .name = "s1ap.KillRequest" },
        { .name = "s1ap.KillResponse" },
        { .name = "s1ap.DownlinkUEAssociatedLPPaTransport" },
        { .name = "s1ap.UplinkUEAssociatedLPPaTransport" },
        { .name = "s1ap.DownlinkNonUEAssociatedLPPaTransport" },
        { .name = "s1ap.UplinkNonUEAssociatedLPPaTransport" },
        { .name = "s1ap.S1AP_PDU" },
        { .name = "s1ap.SONtransferApplicationIdentity" },
        { .name = "s1ap.SONtransferRequestContainer" },
        { .name = "s1ap.SONtransferResponseContainer" },
        { .name = "s1ap.SONtransferCause" },

        { .name = "s1ap.local" },
        { .name = "s1ap.global" },
        { .name = "s1ap.ProtocolIE_Field" },
        { .name = "s1ap.id" },
        { .name = "s1ap.criticality" },
        { .name = "s1ap.value" },
        { .name = "s1ap.ProtocolIE_SingleContainer" },
        { .name = "s1ap.ProtocolExtensionField" },
        { .name = "s1ap.id" },
        { .name = "s1ap.extensionValue" },
        { .name = "s1ap.PrivateIE_Field" },
        { .name = "s1ap.id" },
        { .name = "s1ap.value" },
        { .name = "s1ap.cellBased" },
        { .name = "s1ap.tABased" },
        { .name = "s1ap.pLMNWide" },
        { .name = "s1ap.priorityLevel" },
        { .name = "s1ap.pre_emptionCapability" },
        { .name = "s1ap.pre_emptionVulnerability" },
        { .name = "s1ap.iE_Extensions" },
        { .name = "s1ap.ProtocolIE_SingleContainer" },
        { .name = "s1ap.e_RAB_ID" },
        { .name = "s1ap.uL_COUNTvalue" },
        { .name = "s1ap.dL_COUNTvalue" },
        { .name = "s1ap.receiveStatusofULPDCPSDUs" },
        { .name = "s1ap.PLMNidentity" },
        { .name = "s1ap.cellID_Cancelled" },
        { .name = "s1ap.tAI_Cancelled" },
        { .name = "s1ap.emergencyAreaID_Cancelled" },
        { .name = "s1ap.cellID_Broadcast" },
        { .name = "s1ap.tAI_Broadcast" },
        { .name = "s1ap.emergencyAreaID_Broadcast" },
        { .name = "s1ap.CancelledCellinEAI_Item" },
        { .name = "s1ap.eCGI" },
        { .name = "s1ap.numberOfBroadcasts" },
        { .name = "s1ap.CancelledCellinTAI_Item" },
        { .name = "s1ap.radioNetwork" },
        { .name = "s1ap.transport" },
        { .name = "s1ap.nas" },
        { .name = "s1ap.protocol" },
        { .name = "s1ap.misc" },
        { .name = "s1ap.CellID_Broadcast_Item" },
        { .name = "s1ap.CellID_Cancelled_Item" },
        { .name = "s1ap.cellIdListforMDT" },
        { .name = "s1ap.EUTRAN_CGI" },
        { .name = "s1ap.cdma2000OneXMEID" },
        { .name = "s1ap.cdma2000OneXMSI" },
        { .name = "s1ap.cdma2000OneXPilot" },
        { .name = "s1ap.cell_Size" },
        { .name = "s1ap.pLMNidentity" },

        { .name = "s1ap.lAC" },
        { .name = "s1ap.cI" },
        { .name = "s1ap.rAC" },
        { .name = "s1ap.CSG_IdList_Item" },
        { .name = "s1ap.cSG_Id" },
        { .name = "s1ap.pDCP_SN" },
        { .name = "s1ap.hFN" },
        { .name = "s1ap.procedureCode" },
        { .name = "s1ap.triggeringMessage" },
        { .name = "s1ap.procedureCriticality" },
        { .name = "s1ap.iEsCriticalityDiagnostics" },
        { .name = "s1ap.CriticalityDiagnostics_IE_Item" },
        { .name = "s1ap.iECriticality" },
        { .name = "s1ap.iE_ID" },
        { .name = "s1ap.typeOfError" },
        { .name = "s1ap.EUTRAN_CGI" },
        { .name = "s1ap.EmergencyAreaID" },
        { .name = "s1ap.EmergencyAreaID_Broadcast_Item" },
        { .name = "s1ap.emergencyAreaID" },
        { .name = "s1ap.completedCellinEAI" },
        { .name = "s1ap.EmergencyAreaID_Cancelled_Item" },
        { .name = "s1ap.cancelledCellinEAI" },
        { .name = "s1ap.CompletedCellinEAI_Item" },
        { .name = "s1ap.macroENB_ID" },
        { .name = "s1ap.homeENB_ID" },
        { .name = "s1ap.lAI" },
        { .name = "s1ap.eNB_ID" },
        { .name = "s1ap.GUMMEI" },
        { .name = "s1ap.bearers_SubjectToStatusTransferList" },
        { .name = "s1ap.TransportLayerAddress" },
        { .name = "s1ap.PLMNidentity" },
        { .name = "s1ap.ProtocolIE_SingleContainer" },
        { .name = "s1ap.dL_Forwarding" },
        { .name = "s1ap.ProtocolIE_SingleContainer" },
        { .name = "s1ap.cause" },
        { .name = "s1ap.qCI" },
        { .name = "s1ap.allocationRetentionPriority" },
        { .name = "s1ap.gbrQosInformation" },
        { .name = "s1ap.cell_ID" },
        { .name = "s1ap.ForbiddenTAs_Item" },
        { .name = "s1ap.pLMN_Identity" },
        { .name = "s1ap.forbiddenTACs" },
        { .name = "s1ap.TAC" },
        { .name = "s1ap.ForbiddenLAs_Item" },
        { .name = "s1ap.forbiddenLACs" },
        { .name = "s1ap.LAC" },

        { .name = "s1ap.e_RAB_MaximumBitrateDL" },
        { .name = "s1ap.e_RAB_MaximumBitrateUL" },
        { .name = "s1ap.e_RAB_GuaranteedBitrateDL" },
        { .name = "s1ap.e_RAB_GuaranteedBitrateUL" },
        { .name = "s1ap.mME_Group_ID" },
        { .name = "s1ap.mME_Code" },
        { .name = "s1ap.servingPLMN" },
        { .name = "s1ap.equivalentPLMNs" },
        { .name = "s1ap.forbiddenTAs" },
        { .name = "s1ap.forbiddenLAs" },
        { .name = "s1ap.forbiddenInterRATs" },
        { .name = "s1ap.measurementsToActivate" },
        { .name = "s1ap.reportingTriggerMDT" },
        { .name = "s1ap.thresholdeventA2" },
        { .name = "s1ap.periodicReportingMDT" },
        { .name = "s1ap.e_UTRAN_Cell" },
        { .name = "s1ap.uTRAN_Cell" },
        { .name = "s1ap.gERAN_Cell" },
        { .name = "s1ap.global_Cell_ID" },
        { .name = "s1ap.cellType" },
        { .name = "s1ap.time_UE_StayedInCell" },
        { .name = "s1ap.undefined" },
        { .name = "s1ap.loggingInterval" },
        { .name = "s1ap.loggingDuration" },
        { .name = "s1ap.mdt_Activation" },
        { .name = "s1ap.areaScopeOfMDT" },
        { .name = "s1ap.mDTMode" },
        { .name = "s1ap.immediateMDT" },
        { .name = "s1ap.loggedMDT" },
        { .name = "s1ap.threshold_RSRP" },
        { .name = "s1ap.threshold_RSRQ" },
        { .name = "s1ap.overloadAction" },
        { .name = "s1ap.reportInterval" },
        { .name = "s1ap.reportAmount" },
        { .name = "s1ap.eventType" },
        { .name = "s1ap.reportArea" },
        { .name = "s1ap.rIMInformation" },
        { .name = "s1ap.rIMRoutingAddress" },
        { .name = "s1ap.gERAN_Cell_ID" },
        { .name = "s1ap.targetRNC_ID" },
        { .name = "s1ap.nextHopChainingCount" },
        { .name = "s1ap.nextHopParameter" },
        { .name = "s1ap.sONInformationRequest" },
        { .name = "s1ap.sONInformationReply" },
        { .name = "s1ap.x2TNLConfigurationInfo" },
        { .name = "s1ap.targeteNB_ID" },
        { .name = "s1ap.sourceeNB_ID" },
        { .name = "s1ap.sONInformation" },
        { .name = "s1ap.global_ENB_ID" },
        { .name = "s1ap.selected_TAI" },
        { .name = "s1ap.rRC_Container" },


        { .name = "s1ap.e_RABInformationList" },
        { .name = "s1ap.targetCell_ID" },
        { .name = "s1ap.subscriberProfileIDforRFP" },
        { .name = "s1ap.uE_HistoryInformation" },
        { .name = "s1ap.ServedGUMMEIsItem" },
        { .name = "s1ap.servedPLMNs" },
        { .name = "s1ap.servedGroupIDs" },
        { .name = "s1ap.servedMMECs" },
        { .name = "s1ap.MME_Group_ID" },
        { .name = "s1ap.MME_Code" },
        { .name = "s1ap.PLMNidentity" },
        { .name = "s1ap.SupportedTAs_Item" },
        { .name = "s1ap.tAC" },
        { .name = "s1ap.broadcastPLMNs" },
        { .name = "s1ap.stratumLevel" },
        { .name = "s1ap.synchronizationStatus" },
        { .name = "s1ap.mMEC" },
        { .name = "s1ap.m_TMSI" },
        { .name = "s1ap.TAI" },
        { .name = "s1ap.TAI_Broadcast_Item" },
        { .name = "s1ap.tAI" },
        { .name = "s1ap.completedCellinTAI" },
        { .name = "s1ap.TAI_Cancelled_Item" },
        { .name = "s1ap.cancelledCellinTAI" },
        { .name = "s1ap.tAListforMDT" },
        { .name = "s1ap.TAC" },
        { .name = "s1ap.CompletedCellinTAI_Item" },
        { .name = "s1ap.cGI" },
        { .name = "s1ap.rNC_ID" },
        { .name = "s1ap.extendedRNC_ID" },
        { .name = "s1ap.measurementThreshold" },
        { .name = "s1ap.e_UTRAN_Trace_ID" },
        { .name = "s1ap.interfacesToTrace" },
        { .name = "s1ap.traceDepth" },
        { .name = "s1ap.traceCollectionEntityIPAddress" },
        { .name = "s1ap.uEaggregateMaximumBitRateDL" },
        { .name = "s1ap.uEaggregateMaximumBitRateUL" },
        { .name = "s1ap.uE_S1AP_ID_pair" },
        { .name = "s1ap.mME_UE_S1AP_ID" },
        { .name = "s1ap.eNB_UE_S1AP_ID" },
        { .name = "s1ap.LastVisitedCell_Item" },
        { .name = "s1ap.s_TMSI" },
        { .name = "s1ap.iMSI" },
        { .name = "s1ap.encryptionAlgorithms" },
        { .name = "s1ap.integrityProtectionAlgorithms" },

        { .name = "s1ap.cellIDList" },
        { .name = "s1ap.trackingAreaListforWarning" },
        { .name = "s1ap.emergencyAreaIDList" },
        { .name = "s1ap.eNBX2TransportLayerAddresses" },
        { .name = "s1ap.ENBX2ExtTLA" },
        { .name = "s1ap.iPsecTLA" },
        { .name = "s1ap.gTPTLAa" },
        { .name = "s1ap.TransportLayerAddress" },
        { .name = "s1ap.protocolIEs" },
        { .name = "s1ap.dL_transportLayerAddress" },
        { .name = "s1ap.dL_gTP_TEID" },
        { .name = "s1ap.uL_TransportLayerAddress" },
        { .name = "s1ap.uL_GTP_TEID" },
        { .name = "s1ap.transportLayerAddress" },
        { .name = "s1ap.gTP_TEID" },
        { .name = "s1ap.e_RABlevelQosParameters" },
        { .name = "s1ap.ProtocolIE_SingleContainer" },
        { .name = "s1ap.nAS_PDU" },
        { .name = "s1ap.s1_Interface" },
        { .name = "s1ap.partOfS1_Interface" },
        { .name = "s1ap.rIMTransfer" },
        { .name = "s1ap.privateIEs" },
        { .name = "s1ap.initiatingMessage" },
        { .name = "s1ap.successfulOutcome" },
        { .name = "s1ap.unsuccessfulOutcome" },

        { .name = "s1ap.value" },
        { .name = "s1ap.cellLoadReporting" },
        { .name = "s1ap.multiCellLoadReporting" },
        { .name = "s1ap.eventTriggeredCellLoadReporting" },
        { .name = "s1ap.hOReporting" },
        { .name = "s1ap.cellLoadReporting" },
        { .name = "s1ap.multiCellLoadReporting" },
        { .name = "s1ap.eventTriggeredCellLoadReporting" },
        { .name = "s1ap.hOReporting" },
        { .name = "s1ap.cellLoadReporting" },
        { .name = "s1ap.multiCellLoadReporting" },
        { .name = "s1ap.eventTriggeredCellLoadReporting" },
        { .name = "s1ap.hOReporting" },
        { .name = "s1ap.eUTRAN" },
        { .name = "s1ap.uTRAN" },
        { .name = "s1ap.gERAN" },
        { .name = "s1ap.compositeAvailableCapacityGroup" },
        { .name = "s1ap.eUTRAN" },
        { .name = "s1ap.IRAT_Cell_ID" },
        { .name = "s1ap.requestedCellList" },
        { .name = "s1ap.cell_ID" },
        { .name = "s1ap.ReportingCellList_Item" },
        { .name = "s1ap.reportingCellList" },
        { .name = "s1ap.cellLoadReportingResponse" },
        { .name = "s1ap.numberOfMeasurementReportingLevels" },
        { .name = "s1ap.overloadFlag" },
        { .name = "s1ap.hoType" },
        { .name = "s1ap.hoReportType" },
        { .name = "s1ap.hosourceID" },
        { .name = "s1ap.hoTargetID" },
        { .name = "s1ap.candidateCellList" },
        { .name = "s1ap.IRAT_Cell_ID" },

#if 0
    { "Bearers-SubjectToStatusTransfer-Item",       PDU_FT_UINT32,  0,              0 },
    { "BroadcastCancelledAreaList",                 PDU_FT_UINT32,  0,              0 },
    { "BroadcastCompletedAreaList",                 PDU_FT_UINT32,  0,              0 },
    { "Cause",                                      PDU_FT_UINT8,   0xF0,           0 },
    { "CellAccessMode",                             PDU_FT_UINT32,  0,              0 },
    { "Cdma2000PDU",                                PDU_FT_UINT32,  0,              0 },
    { "Cdma2000RATType",                            PDU_FT_UINT32,  0,              0 },
    { "Cdma2000SectorID",                           PDU_FT_UINT32,  0,              0 },
    { "Cdma2000HOStatus",                           PDU_FT_UINT32,  0,              0 },
    { "Cdma2000HORequiredIndication",               PDU_FT_UINT32,  0,              0 },
    { "Cdma2000OneXSRVCCInfo",                      PDU_FT_UINT32,  0,              0 },
    { "Cdma2000OneXRAND",                           PDU_FT_UINT32,  0,              0 },
    { "CNDomain",                                   PDU_FT_UINT8,   0x80,           0 },
    { "ConcurrentWarningMessageIndicator",          PDU_FT_UINT32,  0,              0 },
    { "Correlation-ID",                             PDU_FT_UINT32,  0,              0 },
    { "CSFallbackIndicator",                        PDU_FT_UINT32,  0,              0 },
    { "CSG-Id",                                     PDU_FT_UINT32,  0,              0 },
    { "CSG-IdList",                                 PDU_FT_UINT32,  0,              0 },
    { "CSGMembershipStatus",                        PDU_FT_UINT32,  0,              0 },
    { "CriticalityDiagnostics",                     PDU_FT_UINT32,  0,              0 },
    { "DataCodingScheme",                           PDU_FT_UINT32,  0,              0 },
    { "Direct-Forwarding-Path-Availability",        PDU_FT_UINT32,  0,              0 },
    { "Data-Forwarding-Not-Possible",               PDU_FT_UINT32,  0,              0 },
    { "Global-ENB-ID",                              PDU_FT_UINT32,  0,              0 },
    { "GUMMEIList",                                 PDU_FT_UINT32,  0,              0 },
    { "ENB-StatusTransfer-TransparentContainer",    PDU_FT_UINT32,  0,              0 },
    { "ENB-UE-S1AP-ID",                             PDU_FT_UINT16,  0,              0 },
    { "ENBname",                                    PDU_FT_UINT32,  0,              0 },
    { "E-RABInformationListItem",                   PDU_FT_UINT32,  0,              0 },
    { "E-RABList",                                  PDU_FT_UINT32,  0,              0 },
    { "E-RABItem",                                  PDU_FT_UINT32,  0,              0 },
    { "EUTRAN-CGI",                                 PDU_FT_UINT32,  0,              0 },
    { "EUTRANRoundTripDelayEstimationInfo",         PDU_FT_UINT32,  0,              0 },
    { "ExtendedRepetitionPeriod",                   PDU_FT_UINT32,  0,              0 },
    { "GUMMEI",                                     PDU_FT_UINT32,  0,              0 },
    { "GWContextReleaseIndication",                 PDU_FT_UINT32,  0,              0 },
    { "HandoverRestrictionList",                    PDU_FT_UINT32,  0,              0 },
    { "HandoverType",                               PDU_FT_UINT8,   0xF0,           0 },
    { "LAI",                                        PDU_FT_UINT32,  0,              0 },
    { "LPPa-PDU",                                   PDU_FT_UINT32,  0,              0 },
    { "MDT-Configuration",                          PDU_FT_UINT32,  0,              0 },
    { "ManagementBasedMDTAllowed",                  PDU_FT_UINT32,  0,              0 },
    { "MessageIdentifier",                          PDU_FT_UINT32,  0,              0 },
    { "MMEname",                                    PDU_FT_UINT32,  0,              0 },
    { "MMERelaySupportIndicator",                   PDU_FT_UINT32,  0,              0 },
    { "MME-UE-S1AP-ID",                             PDU_FT_UINT32,  0x0FFFFFFF,     0 },
    { "MSClassmark2",                               PDU_FT_UINT32,  0,              0 },
    { "MSClassmark3",                               PDU_FT_UINT32,  0,              0 },
    { "NAS-PDU",                                    PDU_FT_UINT32,  0,              0 },
    { "NASSecurityParametersfromE-UTRAN",           PDU_FT_UINT32,  0,              0 },
    { "NASSecurityParameterstoE-UTRAN",             PDU_FT_UINT32,  0,              0 },
    { "NumberofBroadcastRequest",                   PDU_FT_UINT32,  0,              0 },
    { "OverloadResponse",                           PDU_FT_UINT32,  0,              0 },
    { "PagingDRX",                                  PDU_FT_UINT32,  0,              0 },
    { "PagingPriority",                             PDU_FT_UINT32,  0,              0 },
    { "PS-ServiceNotAvailable",                     PDU_FT_UINT32,  0,              0 },
    { "RelativeMMECapacity",                        PDU_FT_UINT32,  0,              0 },
    { "RelayNode-Indicator",                        PDU_FT_UINT32,  0,              0 },
    { "RequestType",                                PDU_FT_UINT32,  0,              0 },
    { "RepetitionPeriod",                           PDU_FT_UINT32,  0,              0 },
    { "RRC-Establishment-Cause",                    PDU_FT_UINT8,   0xF0,           0 },
    { "Routing-ID",                                 PDU_FT_UINT32,  0,              0 },
    { "SecurityKey",                                PDU_FT_UINT32,  0,              0 },
    { "SecurityContext",                            PDU_FT_UINT32,  0,              0 },
    { "SerialNumber",                               PDU_FT_UINT32,  0,              0 },
    { "SONConfigurationTransfer",                   PDU_FT_UINT32,  0,              0 },
    { "Source-ToTarget-TransparentContainer",       PDU_FT_UINT32,  0,              0 },
    { "SRVCCOperationPossible",                     PDU_FT_UINT32,  0,              0 },
    { "SRVCCHOIndication",                          PDU_FT_UINT32,  0,              0 },
    { "SourceeNB-ToTargeteNB-TransparentContainer", PDU_FT_UINT32,  0,              0 },
    { "ServedGUMMEIs",                              PDU_FT_UINT32,  0,              0 },
    { "ServedPLMNs",                                PDU_FT_UINT32,  0,              0 },
    { "SubscriberProfileIDforRFP",                  PDU_FT_UINT32,  0,              0 },
    { "SupportedTAs",                               PDU_FT_UINT32,  0,              0 },
    { "TimeSynchronizationInfo",                    PDU_FT_UINT32,  0,              0 },
    { "S-TMSI",                                     PDU_FT_UINT32,  0,              0 },
    { "TAI",                                        PDU_FT_UINT32,  0,              0 },
    { "TargetID",                                   PDU_FT_UINT8,   0xE0,           0 },
    { "TargeteNB-ToSourceeNB-TransparentContainer", PDU_FT_UINT32,  0,              0 },
    { "Target-ToSource-TransparentContainer",       PDU_FT_UINT32,  0,              0 },
    { "TimeToWait",                                 PDU_FT_UINT32,  0,              0 },
    { "TransportLayerAddress",                      PDU_FT_HEX32,   0,              0 },
    { "TraceActivation",                            PDU_FT_UINT32,  0,              0 },
    { "TrafficLoadReductionIndication",             PDU_FT_UINT32,  0,              0 },
    { "UEAggregateMaximumBitrate",                  PDU_FT_UINT32,  0,              0 },
    { "UE-S1AP-IDs",                                PDU_FT_UINT32,  0,              0 },
    { "UE-associatedLogicalS1-ConnectionItem",      PDU_FT_UINT32,  0,              0 },
    { "UEIdentityIndexValue",                       PDU_FT_UINT32,  0,              0 },
    { "UEPagingID",                                 PDU_FT_UINT32,  0,              0 },
    { "UERadioCapability",                          PDU_FT_UINT32,  0,              0 },
    { "UESecurityCapabilities",                     PDU_FT_UINT32,  0,              0 },
    { "WarningAreaList",                            PDU_FT_UINT32,  0,              0 },
    { "WarningType",                                PDU_FT_UINT32,  0,              0 },
    { "WarningSecurityInfo",                        PDU_FT_UINT32,  0,              0 },
    { "WarningMessageContents",                     PDU_FT_UINT32,  0,              0 },
    { "X2TNLConfigurationInfo",                     PDU_FT_UINT32,  0,              0 },
    { "ENBX2ExtTLAs",                               PDU_FT_UINT32,  0,              0 },
    { "HandoverRequired",                           PDU_FT_UINT32,  0,              0 },
    { "HandoverCommand",                            PDU_FT_UINT32,  0,              0 },
    { "E-RABSubjecttoDataForwardingList",           PDU_FT_BYTES,   0,              PDU_FF_SECTION },
    { "E-RABDataForwardingItem",                    PDU_FT_BYTES,   0,              PDU_FF_SECTION },
    { "HandoverPreparationFailure",                 PDU_FT_UINT32,  0,              0 },
    { "HandoverRequest",                            PDU_FT_UINT32,  0,              0 },
    { "E-RABToBeSetupListHOReq",                    PDU_FT_UINT32,  0,              0 },
    { "E-RABToBeSetupItemHOReq",                    PDU_FT_UINT32,  0,              0 },
    { "HandoverRequestAcknowledge",                 PDU_FT_UINT32,  0,              0 },
    { "E-RABAdmittedList",                          PDU_FT_UINT32,  0,              0 },
    { "E-RABAdmittedItem",                          PDU_FT_UINT32,  0,              0 },
    { "E-RABFailedtoSetupListHOReqAck",             PDU_FT_UINT32,  0,              0 },
    { "E-RABFailedToSetupItemHOReqAck",             PDU_FT_UINT32,  0,              0 },
    { "HandoverFailure",                            PDU_FT_UINT32,  0,              0 },
    { "HandoverNotify",                             PDU_FT_UINT32,  0,              0 },
    { "PathSwitchRequest",                          PDU_FT_UINT32,  0,              0 },
    { "E-RABToBeSwitchedDLList",                    PDU_FT_UINT32,  0,              0 },
    { "E-RABToBeSwitchedDLItem",                    PDU_FT_UINT32,  0,              0 },
    { "PathSwitchRequestAcknowledge",               PDU_FT_UINT32,  0,              0 },
    { "E-RABToBeSwitchedULList",                    PDU_FT_UINT32,  0,              0 },
    { "E-RABToBeSwitchedULItem",                    PDU_FT_UINT32,  0,              0 },
    { "PathSwitchRequestFailure",                   PDU_FT_UINT32,  0,              0 },
    { "HandoverCancel",                             PDU_FT_UINT32,  0,              0 },
    { "HandoverCancelAcknowledge",                  PDU_FT_UINT32,  0,              0 },
    { "E-RABSetupRequest",                          PDU_FT_UINT32,  0,              0 },
    { "E-RABToBeSetupListBearerSUReq",              PDU_FT_UINT32,  0,              0 },
    { "E-RABToBeSetupItemBearerSUReq",              PDU_FT_UINT32,  0,              0 },
    { "E-RABSetupResponse",                         PDU_FT_UINT32,  0,              0 },
    { "E-RABSetupListBearerSURes",                  PDU_FT_UINT32,  0,              0 },
    { "E-RABSetupItemBearerSURes",                  PDU_FT_UINT32,  0,              0 },
    { "E-RABModifyRequest",                         PDU_FT_UINT32,  0,              0 },
    { "E-RABToBeModifiedListBearerModReq",          PDU_FT_UINT32,  0,              0 },
    { "E-RABToBeModifiedItemBearerModReq",          PDU_FT_UINT32,  0,              0 },
    { "E-RABModifyResponse",                        PDU_FT_UINT32,  0,              0 },
    { "E-RABModifyListBearerModRes",                PDU_FT_UINT32,  0,              0 },
    { "E-RABModifyItemBearerModRes",                PDU_FT_UINT32,  0,              0 },
    { "E-RABReleaseCommand",                        PDU_FT_UINT32,  0,              0 },
    { "E-RABReleaseResponse",                       PDU_FT_UINT32,  0,              0 },
    { "E-RABReleaseListBearerRelComp",              PDU_FT_UINT32,  0,              0 },
    { "E-RABReleaseItemBearerRelComp",              PDU_FT_UINT32,  0,              0 },
    { "E-RABReleaseIndication",                     PDU_FT_UINT32,  0,              0 },
    { "InitialContextSetupRequest",                 PDU_FT_UINT32,  0,              0 },
    { "E-RABToBeSetupListCtxtSUReq",                PDU_FT_UINT32,  0,              0 },
    { "E-RABToBeSetupItemCtxtSUReq",                PDU_FT_UINT32,  0,              0 },
    { "InitialContextSetupResponse",                PDU_FT_UINT32,  0,              0 },
    { "E-RABSetupListCtxtSURes",                    PDU_FT_UINT32,  0,              0 },
    { "E-RABSetupItemCtxtSURes",                    PDU_FT_UINT32,  0,              0 },
    { "InitialContextSetupFailure",                 PDU_FT_UINT32,  0,              0 },
    { "Paging",                                     PDU_FT_UINT32,  0,              0 },
    { "TAIList",                                    PDU_FT_UINT32,  0,              0 },
    { "TAIItem",                                    PDU_FT_UINT32,  0,              0 },
    { "UEContextReleaseRequest",                    PDU_FT_UINT32,  0,              0 },
    { "UEContextReleaseCommand",                    PDU_FT_UINT32,  0,              0 },
    { "UEContextReleaseComplete",                   PDU_FT_UINT32,  0,              0 },
    { "UEContextModificationRequest",               PDU_FT_UINT32,  0,              0 },
    { "UEContextModificationResponse",              PDU_FT_UINT32,  0,              0 },
    { "UEContextModificationFailure",               PDU_FT_UINT32,  0,              0 },
    { "DownlinkNASTransport",                       PDU_FT_UINT32,  0,              0 },
    { "InitialUEMessage",                           PDU_FT_UINT32,  0,              0 },
    { "UplinkNASTransport",                         PDU_FT_UINT32,  0,              0 },
    { "NASNonDeliveryIndication",                   PDU_FT_UINT32,  0,              0 },
    { "Reset",                                      PDU_FT_UINT32,  0,              0 },
    { "ResetType",                                  PDU_FT_UINT32,  0,              0 },
    { "ResetAcknowledge",                           PDU_FT_UINT32,  0,              0 },
    { "UE-associatedLogicalS1-ConnectionListResAck",PDU_FT_UINT32,  0,              0 },
    { "ErrorIndication",                            PDU_FT_UINT32,  0,              0 },
    { "S1SetupRequest",                             PDU_FT_UINT32,  0,              0 },
    { "S1SetupResponse",                            PDU_FT_UINT32,  0,              0 },
    { "S1SetupFailure",                             PDU_FT_UINT32,  0,              0 },
    { "ENBConfigurationUpdate",                     PDU_FT_UINT32,  0,              0 },
    { "ENBConfigurationUpdateAcknowledge",          PDU_FT_UINT32,  0,              0 },
    { "ENBConfigurationUpdateFailure",              PDU_FT_UINT32,  0,              0 },
    { "MMEConfigurationUpdate",                     PDU_FT_UINT32,  0,              0 },
    { "MMEConfigurationUpdateAcknowledge",          PDU_FT_UINT32,  0,              0 },
    { "MMEConfigurationUpdateFailure",              PDU_FT_UINT32,  0,              0 },
    { "DownlinkS1cdma2000tunneling",                PDU_FT_UINT32,  0,              0 },
    { "UplinkS1cdma2000tunneling",                  PDU_FT_UINT32,  0,              0 },
    { "UECapabilityInfoIndication",                 PDU_FT_UINT32,  0,              0 },
    { "ENBStatusTransfer",                          PDU_FT_UINT32,  0,              0 },
    { "MMEStatusTransfer",                          PDU_FT_UINT32,  0,              0 },
    { "TraceStart",                                 PDU_FT_UINT32,  0,              0 },
    { "TraceFailureIndication",                     PDU_FT_UINT32,  0,              0 },
    { "DeactivateTrace",                            PDU_FT_UINT32,  0,              0 },
    { "CellTrafficTrace",                           PDU_FT_UINT32,  0,              0 },
    { "LocationReportingControl",                   PDU_FT_UINT32,  0,              0 },
    { "LocationReportingFailureIndication",         PDU_FT_UINT32,  0,              0 },
    { "LocationReport",                             PDU_FT_UINT32,  0,              0 },
    { "OverloadStart",                              PDU_FT_UINT32,  0,              0 },
    { "OverloadStop",                               PDU_FT_UINT32,  0,              0 },
    { "WriteReplaceWarningRequest",                 PDU_FT_UINT32,  0,              0 },
    { "WriteReplaceWarningResponse",                PDU_FT_UINT32,  0,              0 },
    { "ENBDirectInformationTransfer",               PDU_FT_UINT32,  0,              0 },
    { "Inter-SystemInformationTransferType",        PDU_FT_UINT32,  0,              0 },
    { "MMEDirectInformationTransfer",               PDU_FT_UINT32,  0,              0 },
    { "ENBConfigurationTransfer",                   PDU_FT_UINT32,  0,              0 },
    { "MMEConfigurationTransfer",                   PDU_FT_UINT32,  0,              0 },
    { "PrivateMessage",                             PDU_FT_UINT32,  0,              0 },
    { "KillRequest",                                PDU_FT_UINT32,  0,              0 },
    { "KillResponse",                               PDU_FT_UINT32,  0,              0 },
    { "DownlinkUEAssociatedLPPaTransport",          PDU_FT_UINT32,  0,              0 },
    { "UplinkUEAssociatedLPPaTransport",            PDU_FT_UINT32,  0,              0 },
    { "DownlinkNonUEAssociatedLPPaTransport",       PDU_FT_UINT32,  0,              0 },
    { "UplinkNonUEAssociatedLPPaTransport",         PDU_FT_UINT32,  0,              0 },
    { "S1AP-PDU",                                   PDU_FT_BYTES,   0,              PDU_FF_SECTION },
    { "SONtransferApplicationIdentity",             PDU_FT_UINT32,  0,              0 },
    { "SONtransferRequestContainer",                PDU_FT_UINT32,  0,              0 },
    { "SONtransferResponseContainer",               PDU_FT_UINT32,  0,              0 },
    { "SONtransferCause",                           PDU_FT_UINT32,  0,              0 },
    { "local",                                      PDU_FT_UINT32,  0,              0 },
    { "global",                                     PDU_FT_UINT32,  0,              0 },
    { "ProtocolIE-Field",                           PDU_FT_BYTES,   0,              PDU_FF_SECTION },
    { "id",                                         PDU_FT_UINT16,  0,              0 },
    { "criticality",                                PDU_FT_UINT16,  0x4000,         0 },
    { "valsize",                                    PDU_FT_UINT16,  0x0FFF,         PDU_FF_INVISIBLE },
    { "value",                                      PDU_FT_BYTES ,  0,              PDU_FF_SECTION },
    { "ProtocolIE-SingleContainer",                 PDU_FT_UINT32,  0,              0 },
    { "ProtocolExtensionField",                     PDU_FT_UINT32,  0,              0 },
    { "id",                                         PDU_FT_UINT32,  0,              0 },
    { "extensionValue",                             PDU_FT_UINT32,  0,              0 },
    { "PrivateIE-Field",                            PDU_FT_UINT32,  0,              0 },
    { "id",                                         PDU_FT_UINT32,  0,              0 },
    { "value",                                      PDU_FT_UINT32,  0,              0 },
    { "cellBased",                                  PDU_FT_UINT32,  0,              0 },
    { "tABased",                                    PDU_FT_UINT32,  0,              0 },
    { "pLMNWide",                                   PDU_FT_UINT32,  0,              0 },
    { "priorityLevel",                              PDU_FT_UINT32,  0,              0 },
    { "pre-emptionCapability",                      PDU_FT_UINT32,  0,              0 },
    { "pre-emptionVulnerability",                   PDU_FT_UINT32,  0,              0 },
    { "iE-Extensions",                              PDU_FT_UINT32,  0,              0 },
    { "ProtocolIE-SingleContainer",                 PDU_FT_UINT32,  0,              0 },
    { "e-RAB-ID",                                   PDU_FT_HEX8,    0,              0 },
    { "uL-COUNTvalue",                              PDU_FT_UINT32,  0,              0 },
    { "dL-COUNTvalue",                              PDU_FT_UINT32,  0,              0 },
    { "receiveStatusofULPDCPSDUs",                  PDU_FT_UINT32,  0,              0 },
    { "PLMNidentity",                               PDU_FT_HEX24,   0,              0 },
    { "cellID-Cancelled",                           PDU_FT_UINT32,  0,              0 },
    { "tAI-Cancelled",                              PDU_FT_UINT32,  0,              0 },
    { "emergencyAreaID-Cancelled",                  PDU_FT_UINT32,  0,              0 },
    { "cellID-Broadcast",                           PDU_FT_UINT32,  0,              0 },
    { "tAI-Broadcast",                              PDU_FT_UINT32,  0,              0 },
    { "emergencyAreaID-Broadcast",                  PDU_FT_UINT32,  0,              0 },
    { "CancelledCellinEAI-Item",                    PDU_FT_UINT32,  0,              0 },
    { "eCGI",                                       PDU_FT_UINT32,  0,              0 },
    { "numberOfBroadcasts",                         PDU_FT_UINT32,  0,              0 },
    { "CancelledCellinTAI-Item",                    PDU_FT_UINT32,  0,              0 },
    { "radioNetwork",                               PDU_FT_UINT16,  0x0FE0,         0 },
    { "transport",                                  PDU_FT_UINT8,   0x0F,           0 },
    { "nas",                                        PDU_FT_UINT8,   0x07,           0 },
    { "protocol",                                   PDU_FT_UINT8,   0x0F,           0 },
    { "misc",                                       PDU_FT_UINT8,   0x0F,           0 },
    { "CellID-Broadcast-Item",                      PDU_FT_UINT32,  0,              0 },
    { "CellID-Cancelled-Item",                      PDU_FT_UINT32,  0,              0 },
    { "cellIdListforMDT",                           PDU_FT_UINT32,  0,              0 },
    { "EUTRAN-CGI",                                 PDU_FT_UINT32,  0,              0 },
    { "cdma2000OneXMEID",                           PDU_FT_UINT32,  0,              0 },
    { "cdma2000OneXMSI",                            PDU_FT_UINT32,  0,              0 },
    { "cdma2000OneXPilot",                          PDU_FT_UINT32,  0,              0 },
    { "cell-Size",                                  PDU_FT_UINT32,  0,              0 },
    { "pLMNidentity",                               PDU_FT_UINT32,  0,              0 },
    { "lAC",                                        PDU_FT_HEX16,   0,              0 },
    { "cI",                                         PDU_FT_UINT32,  0,              0 },
    { "rAC",                                        PDU_FT_HEX8,    0,              0 },
    { "CSG-IdList-Item",                            PDU_FT_UINT32,  0,              0 },
    { "cSG-Id",                                     PDU_FT_UINT32,  0,              0 },
    { "pDCP-SN",                                    PDU_FT_UINT32,  0,              0 },
    { "hFN",                                        PDU_FT_UINT32,  0,              0 },
    { "procedureCode",                              PDU_FT_UINT8,   0,              0 },
    { "triggeringMessage",                          PDU_FT_UINT32,  0,              0 },
    { "procedureCriticality",                       PDU_FT_UINT32,  0,              0 },
    { "iEsCriticalityDiagnostics",                  PDU_FT_UINT32,  0,              0 },
    { "CriticalityDiagnostics-IE-Item",             PDU_FT_UINT32,  0,              0 },
    { "iECriticality",                              PDU_FT_UINT32,  0,              0 },
    { "iE-ID",                                      PDU_FT_UINT32,  0,              0 },
    { "typeOfError",                                PDU_FT_UINT32,  0,              0 },
    { "EUTRAN-CGI",                                 PDU_FT_UINT32,  0,              0 },
    { "EmergencyAreaID",                            PDU_FT_UINT32,  0,              0 },
    { "EmergencyAreaID-Broadcast-Item",             PDU_FT_UINT32,  0,              0 },
    { "emergencyAreaID",                            PDU_FT_UINT32,  0,              0 },
    { "completedCellinEAI",                         PDU_FT_UINT32,  0,              0 },
    { "EmergencyAreaID-Cancelled-Item",             PDU_FT_UINT32,  0,              0 },
    { "cancelledCellinEAI",                         PDU_FT_UINT32,  0,              0 },
    { "CompletedCellinEAI-Item",                    PDU_FT_UINT32,  0,              0 },
    { "macroENB-ID",                                PDU_FT_HEX24,   0,              0 },
    { "homeENB-ID",                                 PDU_FT_HEX24,   0,              0 },
    { "lAI",                                        PDU_FT_UINT32,  0,              0 },
    { "eNB-ID",                                     PDU_FT_UINT8,   0,              0 },
    { "GUMMEI",                                     PDU_FT_UINT32,  0,              0 },
    { "bearers-SubjectToStatusTransferList",        PDU_FT_UINT32,  0,              0 },
    { "TransportLayerAddress",                      PDU_FT_HEX32,   0,              0 },
    { "PLMNidentity",                               PDU_FT_UINT32,  0,              0 },
    { "ProtocolIE-SingleContainer",                 PDU_FT_UINT32,  0,              0 },
    { "dL-Forwarding",                              PDU_FT_UINT32,  0,              0 },
    { "ProtocolIE-SingleContainer",                 PDU_FT_UINT32,  0,              0 },
    { "cause",                                      PDU_FT_UINT8,   0xE0,           0 },
    { "qCI",                                        PDU_FT_UINT8,   0,              0 },
    { "allocationRetentionPriority",                PDU_FT_UINT32,  0,              0 },
    { "gbrQosInformation",                          PDU_FT_UINT32,  0,              0 },
    { "cell-ID",                                    PDU_FT_HEX32,   0,              0 },
    { "ForbiddenTAs-Item",                          PDU_FT_UINT32,  0,              0 },
    { "pLMN-Identity",                              PDU_FT_UINT32,  0,              0 },
    { "forbiddenTACs",                              PDU_FT_UINT32,  0,              0 },
    { "TAC",                                        PDU_FT_HEX16,   0,              0 },
    { "ForbiddenLAs-Item",                          PDU_FT_UINT32,  0,              0 },
    { "forbiddenLACs",                              PDU_FT_UINT32,  0,              0 },
    { "LAC",                                        PDU_FT_UINT32,  0,              0 },
    { "e-RAB-MaximumBitrateDL",                     PDU_FT_UINT32,  0,              0 },
    { "e-RAB-MaximumBitrateUL",                     PDU_FT_UINT32,  0,              0 },
    { "e-RAB-GuaranteedBitrateDL",                  PDU_FT_UINT32,  0,              0 },
    { "e-RAB-GuaranteedBitrateUL",                  PDU_FT_UINT32,  0,              0 },
    { "mME-Group-ID",                               PDU_FT_UINT32,  0,              0 },
    { "mME-Code",                                   PDU_FT_UINT32,  0,              0 },
    { "servingPLMN",                                PDU_FT_UINT32,  0,              0 },
    { "equivalentPLMNs",                            PDU_FT_UINT32,  0,              0 },
    { "forbiddenTAs",                               PDU_FT_UINT32,  0,              0 },
    { "forbiddenLAs",                               PDU_FT_UINT32,  0,              0 },
    { "forbiddenInterRATs",                         PDU_FT_UINT32,  0,              0 },
    { "measurementsToActivate",                     PDU_FT_UINT32,  0,              0 },
    { "reportingTriggerMDT",                        PDU_FT_UINT32,  0,              0 },
    { "thresholdeventA2",                           PDU_FT_UINT32,  0,              0 },
    { "periodicReportingMDT",                       PDU_FT_UINT32,  0,              0 },
    { "e-UTRAN-Cell",                               PDU_FT_UINT32,  0,              0 },
    { "uTRAN-Cell",                                 PDU_FT_UINT32,  0,              0 },
    { "gERAN-Cell",                                 PDU_FT_UINT32,  0,              0 },
    { "global-Cell-ID",                             PDU_FT_UINT32,  0,              0 },
    { "cellType",                                   PDU_FT_UINT32,  0,              0 },
    { "time-UE-StayedInCell",                       PDU_FT_UINT32,  0,              0 },
    { "undefined",                                  PDU_FT_UINT32,  0,              0 },
    { "loggingInterval",                            PDU_FT_UINT32,  0,              0 },
    { "loggingDuration",                            PDU_FT_UINT32,  0,              0 },
    { "mdt-Activation",                             PDU_FT_UINT32,  0,              0 },
    { "areaScopeOfMDT",                             PDU_FT_UINT32,  0,              0 },
    { "mDTMode",                                    PDU_FT_UINT32,  0,              0 },
    { "immediateMDT",                               PDU_FT_UINT32,  0,              0 },
    { "loggedMDT",                                  PDU_FT_UINT32,  0,              0 },
    { "threshold-RSRP",                             PDU_FT_UINT32,  0,              0 },
    { "threshold-RSRQ",                             PDU_FT_UINT32,  0,              0 },
    { "overloadAction",                             PDU_FT_UINT32,  0,              0 },
    { "reportInterval",                             PDU_FT_UINT32,  0,              0 },
    { "reportAmount",                               PDU_FT_UINT32,  0,              0 },
    { "eventType",                                  PDU_FT_UINT32,  0,              0 },
    { "reportArea",                                 PDU_FT_UINT32,  0,              0 },
    { "rIMInformation",                             PDU_FT_UINT32,  0,              0 },
    { "rIMRoutingAddress",                          PDU_FT_UINT32,  0,              0 },
    { "gERAN-Cell-ID",                              PDU_FT_UINT32,  0,              0 },
    { "targetRNC-ID",                               PDU_FT_BYTES,   0,              PDU_FF_SECTION },
    { "nextHopChainingCount",                       PDU_FT_UINT32,  0,              0 },
    { "nextHopParameter",                           PDU_FT_UINT32,  0,              0 },
    { "sONInformationRequest",                      PDU_FT_UINT32,  0,              0 },
    { "sONInformationReply",                        PDU_FT_UINT32,  0,              0 },
    { "x2TNLConfigurationInfo",                     PDU_FT_UINT32,  0,              0 },
    { "targeteNB-ID",                               PDU_FT_BYTES,   0,              PDU_FF_SECTION },
    { "sourceeNB-ID",                               PDU_FT_UINT32,  0,              0 },
    { "sONInformation",                             PDU_FT_UINT32,  0,              0 },
    { "global-ENB-ID",                              PDU_FT_BYTES,   0,              PDU_FF_SECTION },
    { "selected-TAI",                               PDU_FT_UINT32,  0,              0 },
    { "rRC-Container",                              PDU_FT_UINT32,  0,              0 },
    { "e-RABInformationList",                       PDU_FT_UINT32,  0,              0 },
    { "targetCell-ID",                              PDU_FT_UINT32,  0,              0 },
    { "subscriberProfileIDforRFP",                  PDU_FT_UINT32,  0,              0 },
    { "uE-HistoryInformation",                      PDU_FT_UINT32,  0,              0 },
    { "ServedGUMMEIsItem",                          PDU_FT_UINT32,  0,              0 },
    { "servedPLMNs",                                PDU_FT_UINT32,  0,              0 },
    { "servedGroupIDs",                             PDU_FT_UINT32,  0,              0 },
    { "servedMMECs",                                PDU_FT_UINT32,  0,              0 },
    { "MME-Group-ID",                               PDU_FT_UINT32,  0,              0 },
    { "MME-Code",                                   PDU_FT_UINT32,  0,              0 },
    { "PLMNidentity",                               PDU_FT_UINT32,  0,              0 },
    { "SupportedTAs-Item",                          PDU_FT_UINT32,  0,              0 },
    { "tAC",                                        PDU_FT_HEX16,   0,              0 },
    { "broadcastPLMNs",                             PDU_FT_UINT32,  0,              0 },
    { "stratumLevel",                               PDU_FT_UINT32,  0,              0 },
    { "synchronizationStatus",                      PDU_FT_UINT32,  0,              0 },
    { "mMEC",                                       PDU_FT_HEX16,   0,              0 },
    { "m-TMSI",                                     PDU_FT_HEX32,   0,              0 },
    { "TAI",                                        PDU_FT_UINT32,  0,              0 },
    { "TAI-Broadcast-Item",                         PDU_FT_UINT32,  0,              0 },
    { "tAI",                                        PDU_FT_UINT32,  0,              0 },
    { "completedCellinTAI",                         PDU_FT_UINT32,  0,              0 },
    { "TAI-Cancelled-Item",                         PDU_FT_UINT32,  0,              0 },
    { "cancelledCellinTAI",                         PDU_FT_UINT32,  0,              0 },
    { "tAListforMDT",                               PDU_FT_UINT32,  0,              0 },
    { "TAC",                                        PDU_FT_HEX16,   0,              0 },
    { "CompletedCellinTAI-Item",                    PDU_FT_UINT32,  0,              0 },
    { "cGI",                                        PDU_FT_UINT32,  0,              0 },
    { "rNC-ID",                                     PDU_FT_HEX16,   0,              0 },
    { "extendedRNC-ID",                             PDU_FT_UINT32,  0,              0 },
    { "measurementThreshold",                       PDU_FT_UINT32,  0,              0 },
    { "e-UTRAN-Trace-ID",                           PDU_FT_UINT32,  0,              0 },
    { "interfacesToTrace",                          PDU_FT_UINT32,  0,              0 },
    { "traceDepth",                                 PDU_FT_UINT32,  0,              0 },
    { "traceCollectionEntityIPAddress",             PDU_FT_UINT32,  0,              0 },
    { "uEaggregateMaximumBitRateDL",                PDU_FT_UINT32,  0,              0 },
    { "uEaggregateMaximumBitRateUL",                PDU_FT_UINT32,  0,              0 },
    { "uE-S1AP-ID-pair",                            PDU_FT_UINT32,  0,              0 },
    { "mME-UE-S1AP-ID",                             PDU_FT_UINT32,  0,              0 },
    { "eNB-UE-S1AP-ID",                             PDU_FT_UINT32,  0,              0 },
    { "LastVisitedCell-Item",                       PDU_FT_UINT32,  0,              0 },
    { "s-TMSI",                                     PDU_FT_UINT32,  0,              0 },
    { "iMSI",                                       PDU_FT_UINT32,  0,              0 },
    { "encryptionAlgorithms",                       PDU_FT_UINT32,  0,              0 },
    { "integrityProtectionAlgorithms",              PDU_FT_UINT32,  0,              0 },
    { "cellIDList",                                 PDU_FT_UINT32,  0,              0 },
    { "trackingAreaListforWarning",                 PDU_FT_UINT32,  0,              0 },
    { "emergencyAreaIDList",                        PDU_FT_UINT32,  0,              0 },
    { "eNBX2TransportLayerAddresses",               PDU_FT_UINT32,  0,              0 },
    { "ENBX2ExtTLA",                                PDU_FT_UINT32,  0,              0 },
    { "iPsecTLA",                                   PDU_FT_UINT32,  0,              0 },
    { "gTPTLAa",                                    PDU_FT_UINT32,  0,              0 },
    { "TransportLayerAddress",                      PDU_FT_HEX32,   0,              0 },
    { "protocolIEs",                                PDU_FT_BYTES,   0,              PDU_FF_SECTION },
    { "dL-transportLayerAddress",                   PDU_FT_UINT32,  0,              0 },
    { "dL-gTP-TEID",                                PDU_FT_UINT32,  0,              0 },
    { "uL-TransportLayerAddress",                   PDU_FT_UINT32,  0,              0 },
    { "uL-GTP-TEID",                                PDU_FT_UINT32,  0,              0 },
    { "transportLayerAddress",                      PDU_FT_UINT32,  0,              0 },
    { "gTP-TEID",                                   PDU_FT_HEX32,   0,              0 },
    { "e-RABlevelQosParameters",                    PDU_FT_UINT32,  0,              0 },
    { "ProtocolIE-SingleContainer",                 PDU_FT_UINT32,  0,              0 },
    { "e-RABlevelQoSParameters",                    PDU_FT_UINT32,  0,              0 },
    { "nAS-PDU",                                    PDU_FT_UINT32,  0,              0 },
    { "ProtocolIE-SingleContainer",                 PDU_FT_UINT32,  0,              0 },
    { "ProtocolIE-SingleContainer",                 PDU_FT_UINT32,  0,              0 },
    { "e-RABLevelQoSParameters",                    PDU_FT_UINT32,  0,              0 },
    { "ProtocolIE-SingleContainer",                 PDU_FT_UINT32,  0,              0 },
    { "ProtocolIE-SingleContainer",                 PDU_FT_UINT32,  0,              0 },
    { "ProtocolIE-SingleContainer",                 PDU_FT_UINT32,  0,              0 },
    { "ProtocolIE-SingleContainer",                 PDU_FT_UINT32,  0,              0 },
    { "ProtocolIE-SingleContainer",                 PDU_FT_UINT32,  0,              0 },
    { "s1-Interface",                               PDU_FT_UINT32,  0,              0 },
    { "partOfS1-Interface",                         PDU_FT_UINT32,  0,              0 },
    { "ProtocolIE-SingleContainer",                 PDU_FT_UINT32,  0,              0 },
    { "ProtocolIE-SingleContainer",                 PDU_FT_UINT32,  0,              0 },
    { "rIMTransfer",                                PDU_FT_UINT32,  0,              0 },
    { "privateIEs",                                 PDU_FT_UINT32,  0,              0 },
    { "initiatingMessage",                          PDU_FT_BYTES,   0,              PDU_FF_SECTION },
    { "successfulOutcome",                          PDU_FT_BYTES,   0,              PDU_FF_SECTION },
    { "unsuccessfulOutcome",                        PDU_FT_BYTES,   0,              PDU_FF_SECTION },
    { "value",                                      PDU_FT_UINT32,  0,              0 },
    { "cellLoadReporting",                          PDU_FT_UINT32,  0,              0 },
    { "multiCellLoadReporting",                     PDU_FT_UINT32,  0,              0 },
    { "eventTriggeredCellLoadReporting",            PDU_FT_UINT32,  0,              0 },
    { "hOReporting",                                PDU_FT_UINT32,  0,              0 },
    { "cellLoadReporting",                          PDU_FT_UINT32,  0,              0 },
    { "multiCellLoadReporting",                     PDU_FT_UINT32,  0,              0 },
    { "eventTriggeredCellLoadReporting",            PDU_FT_UINT32,  0,              0 },
    { "hOReporting",                                PDU_FT_UINT32,  0,              0 },
    { "cellLoadReporting",                          PDU_FT_UINT32,  0,              0 },
    { "multiCellLoadReporting",                     PDU_FT_UINT32,  0,              0 },
    { "eventTriggeredCellLoadReporting",            PDU_FT_UINT32,  0,              0 },
    { "hOReporting",                                PDU_FT_UINT32,  0,              0 },
    { "eUTRAN",                                     PDU_FT_UINT32,  0,              0 },
    { "uTRAN",                                      PDU_FT_UINT32,  0,              0 },
    { "gERAN",                                      PDU_FT_UINT32,  0,              0 },
    { "compositeAvailableCapacityGroup",            PDU_FT_UINT32,  0,              0 },
    { "eUTRAN",                                     PDU_FT_UINT32,  0,              0 },
    { "IRAT-Cell-ID",                               PDU_FT_UINT32,  0,              0 },
    { "requestedCellList",                          PDU_FT_UINT32,  0,              0 },
    { "cell-ID",                                    PDU_FT_HEX32,   0,              0 },
    { "ReportingCellList-Item",                     PDU_FT_UINT32,  0,              0 },
    { "reportingCellList",                          PDU_FT_UINT32,  0,              0 },
    { "cellLoadReportingResponse",                  PDU_FT_UINT32,  0,              0 },
    { "numberOfMeasurementReportingLevels",         PDU_FT_UINT32,  0,              0 },
    { "overloadFlag",                               PDU_FT_UINT32,  0,              0 },
    { "hoType",                                     PDU_FT_UINT32,  0,              0 },
    { "hoReportType",                               PDU_FT_UINT32,  0,              0 },
    { "hosourceID",                                 PDU_FT_UINT32,  0,              0 },
    { "hoTargetID",                                 PDU_FT_UINT32,  0,              0 },
    { "candidateCellList",                          PDU_FT_UINT32,  0,              0 },
    { "IRAT-Cell-ID",                               PDU_FT_UINT32,  0,              0 },
#endif
#if 0
    { "MCC",                                        PDU_FT_UINT8,   0,              0 },
    { "MNC",                                        PDU_FT_UINT8,   0,              0 }
#endif
};



s1ap_pie_t s1ap_pies[] = {

    {   0, "MME-UE-S1AP-ID",                     pie_0_MME_UE_ID },
    {   1, "HandoverType",                       pie_1_HandoverType },
    {   2, "Cause",                              pie_2_Cause },
    {   3, "SourceID",                           pie_3_SourceID },
    {   4, "TargetID",                           pie_4_TargetID },
    {   5, NULL,                                 NULL },
    {   6, NULL,                                 NULL },
    {   7, NULL,                                 NULL },
    {   8, "ENB-UE-S1AP-ID",                     pie_8_ENB_UE_ID },
    {   9, NULL,                                 NULL },
    {  10, NULL,                                 NULL },
    {  11, NULL,                                 NULL },
    {  12, "E-RABSubjecttoDataForwardingList",   pie_12_ERABSubjecttoDataForwardingList },
    {  13, "E-RABtoReleaseListHOCmd",            pie_13_ERABtoReleaseListHOCmd },
    {  14, "E-RABDataForwardingItem",            pie_14_ERABDataForwardingItem },
    {  15, "E-RABReleaseItemBearerRelComp",      pie_15_ERABReleaseItemBearerRelComp },
    {  16, "E-RABToBeSetupListBearerSUReq",      pie_16_ERABToBeSetupListBearerSUReq },
    {  17, "E-RABToBeSetupItemBearerSUReq",      pie_17_ERABToBeSetupItemBearerSUReq },
    {  18, "E-RABAdmittedList",                  pie_18_ERABAdmittedList },
    {  19, "E-RABFailedToSetupListHOReqAck",     pie_19_ERABFailedToSetupListHOReqAck },
    {  20, "RABAdmittedItem",                    pie_20_RABAdmittedItem },
    {  21, "E-RABFailedtoSetupItemHOReqAck",     pie_21_ERABFailedtoSetupItemHOReqAck },
    {  22, "E-RABToBeSwitchedDLList",            pie_22_ERABToBeSwitchedDLList },
    {  23, "E-RABToBeSwitchedDLItem",            pie_23_ERABToBeSwitchedDLItem },
    {  24, "E-RABToBeSetupListCtxtSUReq",        pie_24_ERABToBeSetupListCtxtSUReq },
    {  25, "TraceActivation",                    pie_25_TraceActivation },
    {  26, "NAS-PDU",                            pie_26_NAS_PDU },
    {  27, "E-RABToBeSetupItemHOReq",            pie_27_ERABToBeSetupItemHOReq },
    {  28, "E-RABSetupListBearerSURes",          pie_28_ERABSetupListBearerSURes },
    {  29, "E-RABFailedToSetupListBearerSURes",  pie_29_ERABFailedToSetupListBearerSURes },
    {  30, "E-RABToBeModifiedListBearerModReq",  pie_30_ERABToBeModifiedListBearerModReq },
    {  31, "E-RABModifyListBearerModRes",        pie_31_ERABModifyListBearerModRes },
    {  32, "E-RABFailedToModifyList",            pie_32_ERABFailedToModifyList },
    {  33, "E-RABToBeReleasedList",              pie_33_ERABToBeReleasedList },
    {  34, "E-RABFailedToReleaseList",           pie_34_ERABFailedToReleaseList },
    {  35, "E-RABItem",                          pie_35_ERABItem },
    {  36, "E-RABToBeModifiedItemBearerModReq",  pie_36_ERABToBeModifiedItemBearerModReq },
    {  37, "E-RABModifyItemBearerModRes",        pie_37_ERABModifyItemBearerModRes },
    {  38, "E-RABReleaseItem",                   pie_38_ERABReleaseItem },
    {  39, "E-RABSetupItemBearerSURes",          pie_39_ERABSetupItemBearerSURes },

    {  40, "SecurityContext",                    pie_40_SecurityContext },
    {  41, "HandoverRestrictionList",            pie_41_HandoverRestrictionList },
    {  42, NULL,                                 NULL },
    {  43, "UEPagingID",                         pie_43_UEPagingID },
    {  44, "pagingDRX",                          pie_44_pagingDRX },
    {  45, NULL,                                 NULL },
    {  46, "TAIList",                            pie_46_TAIList },
    {  47, "TAIItem",                            pie_47_TAIItem },
    {  48, "E-RABFailedToSetupListCtxtSURes",    pie_48_ERABFailedToSetupListCtxtSURes },
    {  49, "E-RABReleaseItemHOCmd",              pie_49_ERABReleaseItemHOCmd },
    {  50, "E-RABSetupItemCtxtSURes",            pie_50_ERABSetupItemCtxtSURes },
    {  51, "E-RABSetupListCtxtSURes",            pie_51_ERABSetupListCtxtSURes },
    {  52, "E-RABToBeSetupItemCtxtSUReq",        pie_52_ERABToBeSetupItemCtxtSUReq },
    {  53, "E-RABToBeSetupListHOReq",            pie_53_ERABToBeSetupListHOReq },
    {  54, NULL,                                 NULL },
    {  55, "GERANtoLTEHOInformationRes",         pie_55_GERANtoLTEHOInformationRes },
    {  56, NULL,                                 NULL },
    {  57, "E-RABSubjecttoDataForwardingList",   pie_57_UTRANtoLTEHOInformationRes },
    {  58, "UTRANtoLTEHOInformationRes",         pie_58_CriticalityDiagnostics },
    {  59, "Global_ENB_ID",                      pie_59_Global_ENB_ID },
    {  60, "eNBname",                            pie_60_eNBname },
    {  61, "MMEname",                            pie_61_MMEname },
    {  62, NULL,                                 NULL },
    {  63, "ServedPLMNs",                        pie_63_ServedPLMNs },
    {  64, "SupportedTAs",                       pie_64_SupportedTAs },
    {  65, "TimeToWait",                         pie_65_TimeToWait },
    {  66, "UEAggregateMaximumBitrate",          pie_66_UEAggregateMaximumBitrate },
    {  67, "TAI",                                pie_67_TAI },
    {  68, NULL,                                 NULL },
    {  69, "E-RABReleaseListBearerRelComp",      pie_69_ERABReleaseListBearerRelComp },
    {  70, "cdma2000PDU",                        pie_70_cdma2000PDU },
    {  71, "cdma2000RATType",                    pie_71_cdma2000RATType },
    {  72, "cdma2000SectorID",                   pie_72_cdma2000SectorID },
    {  73, "SecurityKey",                        pie_73_SecurityKey },
    {  74, "UERadioCapability",                  pie_74_UERadioCapability },
    {  75, "GUMMEI_ID",                          pie_75_GUMMEI_ID },
    {  76, NULL,                                 NULL },
    {  77, NULL,                                 NULL },
    {  78, "E-RABInformationListItem",           pie_78_ERABInformationListItem },
    {  79, "DirectForwardingPathAvailability",   pie_79_DirectForwardingPathAvailability },

    {  80, "UEIdentityIndexValue",                        pie_80_UEIdentityIndexValue },
    {  81, NULL,                                          NULL },
    {  82, NULL,                                          NULL },
    {  83, "cdma2000HOStatus",                            pie_83_cdma2000HOStatus },
    {  84, "cdma2000HORequiredIndication",                pie_84_cdma2000HORequiredIndication },
    {  85, NULL,                                          NULL },
    {  86, "EUTRANTraceID",                               pie_86_EUTRANTraceID },
    {  87, "RelativeMMECapacity",                         pie_87_RelativeMMECapacity },
    {  88, "SourceMME_UE_S1AP_ID",                        pie_88_SourceMME_UE_S1AP_ID },
    {  89, "Bearers-SubjectToStatusTransfer-Item",        pie_89_BearersSubjectToStatusTransferItem },
    {  90, "eNB_StatusTransferTransparentContainer",      pie_90_eNB_StatusTransferTransparentContainer },
    {  91, "UE-associatedLogicalS1ConnectionItem",        pie_91_UE_associatedLogicalS1ConnectionItem },
    {  92, "ResetType",                                   pie_92_ResetType },
    {  93, "UE-associatedLogicalS1ConnectionListResAck",  pie_93_UE_associatedLogicalS1ConnectionListResAck },
    {  94, "E-RABToBeSwitchedULItem",                     pie_94_ERABToBeSwitchedULItem },
    {  95, "E-RABToBeSwitchedULList",                     pie_95_ERABToBeSwitchedULList },
    {  96, "STMSI",                                       pie_96_STMSI },
    {  97, "cdma2000OneXRAND",                            pie_97_cdma2000OneXRAND },
    {  98, "RequestType",                                 pie_98_RequestType },
    {  99, "UE-S1AP-IDs",                                 pie_99_UE_S1AP_IDs },
    { 100, "EUTRAN-CGI",                                  pie_100_EUTRAN_CGI },
    { 101, "OverloadResponse",                            pie_101_OverloadResponse },
    { 102, "cdma2000OneXSRVCCInfo",                       pie_102_cdma2000OneXSRVCCInfo },
    { 103, "E-RABFailedToBeReleasedList",                 pie_103_ERABFailedToBeReleasedList },
    { 104, "SourceToTargetTransparentContainer",          pie_104_SourceToTargetTransparentContainer },
    { 105, "ServedGUMMEIs",                               pie_105_ServedGUMMEIs },
    { 106, "SubscriberProfileIDforRFP",                   pie_106_SubscriberProfileIDforRFP },
    { 107, "UESecurityCapabilities",                      pie_107_UESecurityCapabilities },
    { 108, "CSFallbackIndicator",                         pie_108_CSFallbackIndicator },
    { 109, "CNDomain",                                    pie_109_CNDomain },
    { 110, "E-RABReleasedList",                           pie_110_ERABReleasedList },
    { 111, "MessageIdentifier",                           pie_111_MessageIdentifier },
    { 112, "SerialNumber",                                pie_112_SerialNumber },
    { 113, "WarningAreaList",                             pie_113_WarningAreaList },
    { 114, "RepetitionPeriod",                            pie_114_RepetitionPeriod },
    { 115, "NumberofBroadcastRequest",                    pie_115_NumberofBroadcastRequest },
    { 116, "WarningType",                                 pie_116_WarningType },
    { 117, "WarningSecurityInfo",                         pie_117_WarningSecurityInfo },
    { 118, "DataCodingScheme",                            pie_118_DataCodingScheme },
    { 119, "WarningMessageContents",                      pie_119_WarningMessageContents },

    { 120, "BroadcastCompletedAreaList",                  pie_120_BroadcastCompletedAreaList },
    { 121, "InterSystemInformationTransferTypeEDT",       pie_121_InterSystemInformationTransferTypeEDT },
    { 122, "InterSystemInformationTransferTypeMDT",       pie_122_InterSystemInformationTransferTypeMDT },
    { 123, "TargetToSourceTransparentContainer",          pie_123_TargetToSourceTransparentContainer },
    { 124, "SRVCCOperationPossible",                      pie_124_SRVCCOperationPossible },
    { 125, "SRVCCHOIndication",                           pie_125_SRVCCHOIndication },
    { 126, "NASDownlinkCount",                            pie_126_NASDownlinkCount },
    { 127, "CSGId",                                       pie_127_CSGId },
    { 128, "CSGIdList",                                   pie_128_CSGIdList },
    { 129, "SONConfigurationTransferECT",                 pie_129_SONConfigurationTransferECT },
    { 130, "SONConfigurationTransferMCT",                 pie_130_SONConfigurationTransferMCT },
    { 131, "TraceCollectionEntityIPAddress",              pie_131_TraceCollectionEntityIPAddress },
    { 132, "MSClassmark2",                                pie_132_MSClassmark2 },
    { 133, "MSClassmark3",                                pie_133_MSClassmark3 },
    { 134, "RRCEstablishmentCause",                       pie_134_RRCEstablishmentCause },
    { 135, "NASSecurityParametersFromEUTRAN",             pie_135_NASSecurityParametersFromEUTRAN },
    { 136, "NASSecurityParametersToEUTRAN",               pie_136_NASSecurityParametersToEUTRAN },
    { 137, "DefaultPagingDRX",                            pie_137_DefaultPagingDRX },
    { 138, "SourceToTargetTransparentContainerSecondary", pie_138_SourceToTargetTransparentContainerSecondary },
    { 139, "TargetToSourceTransparentContainerSecondary", pie_139_TargetToSourceTransparentContainerSecondary },
    { 140, "EUTRANRoundTripDelayEstimationInfo",          pie_140_EUTRANRoundTripDelayEstimationInfo },
    { 141, "BroadcastCancelledAreaList",                  pie_141_BroadcastCancelledAreaList },
    { 142, "ConcurrentWarningMessageIndicator",           pie_142_ConcurrentWarningMessageIndicator },
    { 143, "DataForwardingNotPossible",                   pie_143_DataForwardingNotPossible },
    { 144, "ExtendedRepetitionPeriod",                    pie_144_ExtendedRepetitionPeriod },
    { 145, "CellAccessMode",                              pie_145_CellAccessMode },
    { 146, "CSGMembershipStatus",                         pie_146_CSGMembershipStatus },
    { 147, "LPPaPDU",                                     pie_147_LPPaPDU },
    { 148, "RoutingID",                                   pie_148_RoutingID },
    { 149, "TimeSynchronizationInfo",                     pie_149_TimeSynchronizationInfo },
    { 150, "PSServiceNotAvailable",                       pie_150_PSServiceNotAvailable },
    { 151, "PagingPriority",                              pie_151_PagingPriority },
    { 152, "x2TNLConfigurationInfo",                      pie_152_x2TNLConfigurationInfo },
    { 153, "eNBX2ExtendedTransportLayerAddresses",        pie_153_eNBX2ExtendedTransportLayerAddresses },
    { 154, "E-RABGUMMEIList",                             pie_154_GUMMEIList },
    { 155, "GWTransportLayerAddress",                     pie_155_GWTransportLayerAddress },
    { 156, "CorrelationID",                               pie_156_CorrelationID },
    { 157, "SourceMME_GUMMEI",                            pie_157_SourceMME_GUMMEI },
    { 158, "MME-UE-S1AP-ID-2",                            pie_158_MME_UE_S1AP_ID_2 },
    { 159, "RegisteredLAI",                               pie_159_RegisteredLAI },

    { 160, "RelayNode-Indicator",             pie_160_RelayNode_Indicator },
    { 161, "TrafficLoadReductionIndication",  pie_161_TrafficLoadReductionIndication },
    { 162, "MDTConfiguration",                pie_162_MDTConfiguration },
    { 163, "MMERelaySupportIndicator",        pie_163_MMERelaySupportIndicator },
    { 164, "GWContextReleaseIndication",      pie_164_GWContextReleaseIndication },
    { 165, "ManagementBasedMDTAllowed",       pie_165_ManagementBasedMDTAllowed },
};
const size_t s1ap_pies_sz = sizeof(s1ap_pies) / sizeof(s1ap_pies[0]);

s1ap_proccode_t s1ap_proccodes[] = {
    { 0, "HandoverPreparation"},
    { 1, "HandoverResourceAllocation"},
    { 2, "HandoverNotification"},
    { 3, "PathSwitchRequest"},
    { 4, "HandoverCancel"},
    { 5, "E-RABSetup"},
    { 6, "E-RABModify"},
    { 7, "E-RABRelease"},
    { 8, "E-RABReleaseIndication"},
    { 9, "InitialContextSetup"},
    {10, "Paging"},
    {11, "downlinkNASTransport"},
    {12, "initialUEMessage"},
    {13, "uplinkNASTransport"},
    {14, "Reset"},
    {15, "ErrorIndication"},
    {16, "NASNonDeliveryIndication"},
    {17, "S1Setup"},
    {18, "UEContextReleaseRequest"},
    {19, "DownlinkS1cdma2000tunneling"},
    {20, "UplinkS1cdma2000tunneling"},
    {21, "UEContextModification"},
    {22, "UECapabilityInfoIndication"},
    {23, "UEContextRelease"},
    {24, "eNBStatusTransfer"},
    {25, "MMEStatusTransfer"},
    {26, "DeactivateTrace"},
    {27, "TraceStart"},
    {28, "TraceFailureIndication"},
    {29, "ENBConfigurationUpdate"},
    {30, "MMEConfigurationUpdate"},
    {31, "LocationReportingControl"},
    {32, "LocationReportingFailureIndication"},
    {33, "LocationReport"},
    {34, "OverloadStart"},
    {35, "OverloadStop"},
    {36, "WriteReplaceWarning"},
    {37, "eNBDirectInformationTransfer"},
    {38, "MMEDirectInformationTransfer"},
    {39, "PrivateMessage"},
    {40, "eNBConfigurationTransfer"},
    {41, "MMEConfigurationTransfer"},
    {42, "CellTrafficTrace"},
    {43, "Kill"},
    {44, "downlinkUEAssociatedLPPaTransport"},
    {45, "uplinkUEAssociatedLPPaTransport"},
    {46, "downlinkNonUEAssociatedLPPaTransport"},
    {47, "uplinkNonUEAssociatedLPPaTransport"}
};
const size_t s1ap_proccodes_sz = sizeof(s1ap_proccodes) / sizeof(s1ap_proccodes[0]);
