#include "../pdu.h"
#include "s1ap_dict.h"


struct dict_node
dict_nodes[] = {
    {"S1AP",                "S1 Application Protocol", DICT_NTYPE_PROTO,   DICT_DTYPE_BYTES, true, NULL, NULL},
    {"S1AP-PDU",            "",                        DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"initiatingMessage",   "",                        DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"successfulOutcome",   "",                        DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"unsuccessfulOutcome", "",                        DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"Item",                "",                        DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},

    {"pduType",             "",                        DICT_NTYPE_BITSET,  DICT_DTYPE_UINT8, false,NULL, NULL},
    {"procedureCode",       "",                        DICT_NTYPE_FIELD,   DICT_DTYPE_UINT8, true, NULL, NULL},
    {"critically",          "",                        DICT_NTYPE_BITSET,  DICT_DTYPE_UINT16,true, NULL, NULL},
    {"valueSize",           "",                        DICT_NTYPE_BITSET,  DICT_DTYPE_UINT16,true, NULL, NULL},

    {"value",               "",                        DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},

    {"Paging",              "",                        DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"uplinkNASTransport",  "",                        DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"initialUEMessage",    "",                        DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"UEContextRelease",    "",                        DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"UEContextModificationRequest", "",               DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},

    {"protocolIEs",               "",                  DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"protocolIE-field",          "",                  DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"protocolIE-SingleContainer","",                  DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},

    {"id",                     "",                     DICT_NTYPE_FIELD,   DICT_DTYPE_UINT16,true, NULL, NULL},

        /* ---- */
    {"MME-UE-S1AP-ID",         "",                     DICT_NTYPE_FIELD,   DICT_DTYPE_UINT24,true, NULL, NULL},
    {"ENB-UE-S1AP-ID",         "",                     DICT_NTYPE_FIELD,   DICT_DTYPE_UINT16,true, NULL, NULL},

        /* 2  */
    {"Cause",                  "",                     DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"radioNetwork",           "",                     DICT_NTYPE_FIELD,   DICT_DTYPE_UINT8, true, NULL, NULL},

        /* 43 */
    {"UEPagingID",             "",                     DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"s-TMSI",                 "",                     DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"mMEC",                   "",                     DICT_NTYPE_FIELD,   DICT_DTYPE_HEX16, true, NULL, NULL},
    {"m-TMSI",                 "",                     DICT_NTYPE_FIELD,   DICT_DTYPE_HEX32, true, NULL, NULL},

        /* 46 */
    {"TAIList",                "",                     DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},

        /* 47 */
    {"TAIItem",                "",                     DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"pLMNIdentity",           "",                     DICT_NTYPE_FIELD,   DICT_DTYPE_HEX24, true, NULL, NULL},
    {"tAC",                    "",                     DICT_NTYPE_FIELD,   DICT_DTYPE_HEX16, true, NULL, NULL},
    {"MCC",                    "",                     DICT_NTYPE_BITSET,  DICT_DTYPE_HEX16, true, NULL, NULL},
    {"MNC",                    "",                     DICT_NTYPE_BITSET,  DICT_DTYPE_HEX16, true, NULL, NULL},

        /* 66 */
    {"UEAggregateMaximumBitrate","",                   DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"uEaggregateMaximumBitRateDL","",                 DICT_NTYPE_FIELD,   DICT_DTYPE_UINT32, true, NULL, NULL},
    {"uEaggregateMaximumBitRateUL","",                 DICT_NTYPE_FIELD,   DICT_DTYPE_UINT32, true, NULL, NULL},

        /* 67 */
    {"TAI",                    "",                     DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},

        /* 80 */
    {"UEIdentityIndexValue",   "",                     DICT_NTYPE_FIELD,   DICT_DTYPE_HEX16, true, NULL, NULL},

        /* 99 */
    {"UE_S1AP_IDs",            "",                     DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"uE-S1AP-ID-pair",        "",                     DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},

        /* 100 */
    {"EUTRAN-CGI",             "",                     DICT_NTYPE_SECTION, DICT_DTYPE_BYTES, true, NULL, NULL},
    {"cell-ID",                "",                     DICT_NTYPE_FIELD,   DICT_DTYPE_HEX32, true, NULL, NULL},

        /* 109 */
    {"CNDomain",               "",                     DICT_NTYPE_FIELD,   DICT_DTYPE_UINT8, true, NULL, NULL},

        /* 134 */
    {"RRC-Establishment-Cause","",                     DICT_NTYPE_FIELD,   DICT_DTYPE_UINT8, true, NULL, NULL},

    {NULL,                  NULL,                      0,                  0,                true, NULL, NULL}
};


#define DNT_UINT32 0
struct node {
    char             *name;
    uint32_t          type;
    uint64_t          bitmask;
} nodes[] = {
    { "Bearers-SubjectToStatusTransfer-Item",       DNT_UINT32, 0 },
    { "BroadcastCancelledAreaList",                 DNT_UINT32, 0 },
    { "BroadcastCompletedAreaList",                 DNT_UINT32, 0 },
    { "Cause",                                      DNT_UINT32, 0 },
    { "CellAccessMode",                             DNT_UINT32, 0 },
    { "Cdma2000PDU",                                DNT_UINT32, 0 },
    { "Cdma2000RATType",                            DNT_UINT32, 0 },
    { "Cdma2000SectorID",                           DNT_UINT32, 0 },
    { "Cdma2000HOStatus",                           DNT_UINT32, 0 },
    { "Cdma2000HORequiredIndication",               DNT_UINT32, 0 },
    { "Cdma2000OneXSRVCCInfo",                      DNT_UINT32, 0 },
    { "Cdma2000OneXRAND",                           DNT_UINT32, 0 },
    { "CNDomain",                                   DNT_UINT32, 0 },
    { "ConcurrentWarningMessageIndicator",          DNT_UINT32, 0 },
    { "Correlation-ID",                             DNT_UINT32, 0 },
    { "CSFallbackIndicator",                        DNT_UINT32, 0 },
    { "CSG-Id",                                     DNT_UINT32, 0 },
    { "CSG-IdList",                                 DNT_UINT32, 0 },
    { "CSGMembershipStatus",                        DNT_UINT32, 0 },
    { "CriticalityDiagnostics",                     DNT_UINT32, 0 },
    { "DataCodingScheme",                           DNT_UINT32, 0 },
    { "Direct-Forwarding-Path-Availability",        DNT_UINT32, 0 },
    { "Data-Forwarding-Not-Possible",               DNT_UINT32, 0 },
    { "Global-ENB-ID",                              DNT_UINT32, 0 },
    { "GUMMEIList",                                 DNT_UINT32, 0 },
    { "ENB-StatusTransfer-TransparentContainer",    DNT_UINT32, 0 },
    { "ENB-UE-S1AP-ID",                             DNT_UINT32, 0 },
    { "ENBname",                                    DNT_UINT32, 0 },
    { "E-RABInformationListItem",                   DNT_UINT32, 0 },
    { "E-RABList",                                  DNT_UINT32, 0 },
    { "E-RABItem",                                  DNT_UINT32, 0 },
    { "EUTRAN-CGI",                                 DNT_UINT32, 0 },
    { "EUTRANRoundTripDelayEstimationInfo",         DNT_UINT32, 0 },
    { "ExtendedRepetitionPeriod",                   DNT_UINT32, 0 },
    { "GUMMEI",                                     DNT_UINT32, 0 },
    { "GWContextReleaseIndication",                 DNT_UINT32, 0 },
    { "HandoverRestrictionList",                    DNT_UINT32, 0 },
    { "HandoverType",                               DNT_UINT32, 0 },
    { "LAI",                                        DNT_UINT32, 0 },
    { "LPPa-PDU",                                   DNT_UINT32, 0 },
    { "MDT-Configuration",                          DNT_UINT32, 0 },
    { "ManagementBasedMDTAllowed",                  DNT_UINT32, 0 },
    { "MessageIdentifier",                          DNT_UINT32, 0 },
    { "MMEname",                                    DNT_UINT32, 0 },
    { "MMERelaySupportIndicator",                   DNT_UINT32, 0 },
    { "MME-UE-S1AP-ID",                             DNT_UINT32, 0 },
    { "MSClassmark2",                               DNT_UINT32, 0 },
    { "MSClassmark3",                               DNT_UINT32, 0 },
    { "NAS-PDU",                                    DNT_UINT32, 0 },
    { "NASSecurityParametersfromE-UTRAN",           DNT_UINT32, 0 },
    { "NASSecurityParameterstoE-UTRAN",             DNT_UINT32, 0 },
    { "NumberofBroadcastRequest",                   DNT_UINT32, 0 },
    { "OverloadResponse",                           DNT_UINT32, 0 },
    { "PagingDRX",                                  DNT_UINT32, 0 },
    { "PagingPriority",                             DNT_UINT32, 0 },
    { "PS-ServiceNotAvailable",                     DNT_UINT32, 0 },
    { "RelativeMMECapacity",                        DNT_UINT32, 0 },
    { "RelayNode-Indicator",                        DNT_UINT32, 0 },
    { "RequestType",                                DNT_UINT32, 0 },
    { "RepetitionPeriod",                           DNT_UINT32, 0 },
    { "RRC-Establishment-Cause",                    DNT_UINT32, 0 },
    { "Routing-ID",                                 DNT_UINT32, 0 },
    { "SecurityKey",                                DNT_UINT32, 0 },
    { "SecurityContext",                            DNT_UINT32, 0 },
    { "SerialNumber",                               DNT_UINT32, 0 },
    { "SONConfigurationTransfer",                   DNT_UINT32, 0 },
    { "Source-ToTarget-TransparentContainer",       DNT_UINT32, 0 },
    { "SRVCCOperationPossible",                     DNT_UINT32, 0 },
    { "SRVCCHOIndication",                          DNT_UINT32, 0 },
    { "SourceeNB-ToTargeteNB-TransparentContainer", DNT_UINT32, 0 },
    { "ServedGUMMEIs",                              DNT_UINT32, 0 },
    { "ServedPLMNs",                                DNT_UINT32, 0 },
    { "SubscriberProfileIDforRFP",                  DNT_UINT32, 0 },
    { "SupportedTAs",                               DNT_UINT32, 0 },
    { "TimeSynchronizationInfo",                    DNT_UINT32, 0 },
    { "S-TMSI",                                     DNT_UINT32, 0 },
    { "TAI",                                        DNT_UINT32, 0 },
    { "TargetID",                                   DNT_UINT32, 0 },
    { "TargeteNB-ToSourceeNB-TransparentContainer", DNT_UINT32, 0 },
    { "Target-ToSource-TransparentContainer",       DNT_UINT32, 0 },
    { "TimeToWait",                                 DNT_UINT32, 0 },
    { "TransportLayerAddress",                      DNT_UINT32, 0 },
    { "TraceActivation",                            DNT_UINT32, 0 },
    { "TrafficLoadReductionIndication",             DNT_UINT32, 0 },
    { "UEAggregateMaximumBitrate",                  DNT_UINT32, 0 },
    { "UE-S1AP-IDs",                                DNT_UINT32, 0 },
    { "UE-associatedLogicalS1-ConnectionItem",      DNT_UINT32, 0 },
    { "UEIdentityIndexValue",                       DNT_UINT32, 0 },
    { "UEPagingID",                                 DNT_UINT32, 0 },
    { "UERadioCapability",                          DNT_UINT32, 0 },
    { "UESecurityCapabilities",                     DNT_UINT32, 0 },
    { "WarningAreaList",                            DNT_UINT32, 0 },
    { "WarningType",                                DNT_UINT32, 0 },
    { "WarningSecurityInfo",                        DNT_UINT32, 0 },
    { "WarningMessageContents",                     DNT_UINT32, 0 },
    { "X2TNLConfigurationInfo",                     DNT_UINT32, 0 },
    { "ENBX2ExtTLAs",                               DNT_UINT32, 0 },
    { "HandoverRequired",                           DNT_UINT32, 0 },
    { "HandoverCommand",                            DNT_UINT32, 0 },
    { "E-RABSubjecttoDataForwardingList",           DNT_UINT32, 0 },
    { "E-RABDataForwardingItem",                    DNT_UINT32, 0 },
    { "HandoverPreparationFailure",                 DNT_UINT32, 0 },
    { "HandoverRequest",                            DNT_UINT32, 0 },
    { "E-RABToBeSetupListHOReq",                    DNT_UINT32, 0 },
    { "E-RABToBeSetupItemHOReq",                    DNT_UINT32, 0 },
    { "HandoverRequestAcknowledge",                 DNT_UINT32, 0 },
    { "E-RABAdmittedList",                          DNT_UINT32, 0 },
    { "E-RABAdmittedItem",                          DNT_UINT32, 0 },
    { "E-RABFailedtoSetupListHOReqAck",             DNT_UINT32, 0 },
    { "E-RABFailedToSetupItemHOReqAck",             DNT_UINT32, 0 },
    { "HandoverFailure",                            DNT_UINT32, 0 },
    { "HandoverNotify",                             DNT_UINT32, 0 },
    { "PathSwitchRequest",                          DNT_UINT32, 0 },
    { "E-RABToBeSwitchedDLList",                    DNT_UINT32, 0 },
    { "E-RABToBeSwitchedDLItem",                    DNT_UINT32, 0 },
    { "PathSwitchRequestAcknowledge",               DNT_UINT32, 0 },
    { "E-RABToBeSwitchedULList",                    DNT_UINT32, 0 },
    { "E-RABToBeSwitchedULItem",                    DNT_UINT32, 0 },
    { "PathSwitchRequestFailure",                   DNT_UINT32, 0 },
    { "HandoverCancel",                             DNT_UINT32, 0 },
    { "HandoverCancelAcknowledge",                  DNT_UINT32, 0 },
    { "E-RABSetupRequest",                          DNT_UINT32, 0 },
    { "E-RABToBeSetupListBearerSUReq",              DNT_UINT32, 0 },
    { "E-RABToBeSetupItemBearerSUReq",              DNT_UINT32, 0 },
    { "E-RABSetupResponse",                         DNT_UINT32, 0 },
    { "E-RABSetupListBearerSURes",                  DNT_UINT32, 0 },
    { "E-RABSetupItemBearerSURes",                  DNT_UINT32, 0 },
    { "E-RABModifyRequest",                         DNT_UINT32, 0 },
    { "E-RABToBeModifiedListBearerModReq",          DNT_UINT32, 0 },
    { "E-RABToBeModifiedItemBearerModReq",          DNT_UINT32, 0 },
    { "E-RABModifyResponse",                        DNT_UINT32, 0 },
    { "E-RABModifyListBearerModRes",                DNT_UINT32, 0 },
    { "E-RABModifyItemBearerModRes",                DNT_UINT32, 0 },
    { "E-RABReleaseCommand",                        DNT_UINT32, 0 },
    { "E-RABReleaseResponse",                       DNT_UINT32, 0 },
    { "E-RABReleaseListBearerRelComp",              DNT_UINT32, 0 },
    { "E-RABReleaseItemBearerRelComp",              DNT_UINT32, 0 },
    { "E-RABReleaseIndication",                     DNT_UINT32, 0 },
    { "InitialContextSetupRequest",                 DNT_UINT32, 0 },
    { "E-RABToBeSetupListCtxtSUReq",                DNT_UINT32, 0 },
    { "E-RABToBeSetupItemCtxtSUReq",                DNT_UINT32, 0 },
    { "InitialContextSetupResponse",                DNT_UINT32, 0 },
    { "E-RABSetupListCtxtSURes",                    DNT_UINT32, 0 },
    { "E-RABSetupItemCtxtSURes",                    DNT_UINT32, 0 },
    { "InitialContextSetupFailure",                 DNT_UINT32, 0 },
    { "Paging",                                     DNT_UINT32, 0 },
    { "TAIList",                                    DNT_UINT32, 0 },
    { "TAIItem",                                    DNT_UINT32, 0 },
    { "UEContextReleaseRequest",                    DNT_UINT32, 0 },
    { "UEContextReleaseCommand",                    DNT_UINT32, 0 },
    { "UEContextReleaseComplete",                   DNT_UINT32, 0 },
    { "UEContextModificationRequest",               DNT_UINT32, 0 },
    { "UEContextModificationResponse",              DNT_UINT32, 0 },
    { "UEContextModificationFailure",               DNT_UINT32, 0 },
    { "DownlinkNASTransport",                       DNT_UINT32, 0 },
    { "InitialUEMessage",                           DNT_UINT32, 0 },
    { "UplinkNASTransport",                         DNT_UINT32, 0 },
    { "NASNonDeliveryIndication",                   DNT_UINT32, 0 },
    { "Reset",                                      DNT_UINT32, 0 },
    { "ResetType",                                  DNT_UINT32, 0 },
    { "ResetAcknowledge",                           DNT_UINT32, 0 },
    { "UE-associatedLogicalS1-ConnectionListResAck",DNT_UINT32, 0 },
    { "ErrorIndication",                            DNT_UINT32, 0 },
    { "S1SetupRequest",                             DNT_UINT32, 0 },
    { "S1SetupResponse",                            DNT_UINT32, 0 },
    { "S1SetupFailure",                             DNT_UINT32, 0 },
    { "ENBConfigurationUpdate",                     DNT_UINT32, 0 },
    { "ENBConfigurationUpdateAcknowledge",          DNT_UINT32, 0 },
    { "ENBConfigurationUpdateFailure",              DNT_UINT32, 0 },
    { "MMEConfigurationUpdate",                     DNT_UINT32, 0 },
    { "MMEConfigurationUpdateAcknowledge",          DNT_UINT32, 0 },
    { "MMEConfigurationUpdateFailure",              DNT_UINT32, 0 },
    { "DownlinkS1cdma2000tunneling",                DNT_UINT32, 0 },
    { "UplinkS1cdma2000tunneling",                  DNT_UINT32, 0 },
    { "UECapabilityInfoIndication",                 DNT_UINT32, 0 },
    { "ENBStatusTransfer",                          DNT_UINT32, 0 },
    { "MMEStatusTransfer",                          DNT_UINT32, 0 },
    { "TraceStart",                                 DNT_UINT32, 0 },
    { "TraceFailureIndication",                     DNT_UINT32, 0 },
    { "DeactivateTrace",                            DNT_UINT32, 0 },
    { "CellTrafficTrace",                           DNT_UINT32, 0 },
    { "LocationReportingControl",                   DNT_UINT32, 0 },
    { "LocationReportingFailureIndication",         DNT_UINT32, 0 },
    { "LocationReport",                             DNT_UINT32, 0 },
    { "OverloadStart",                              DNT_UINT32, 0 },
    { "OverloadStop",                               DNT_UINT32, 0 },
    { "WriteReplaceWarningRequest",                 DNT_UINT32, 0 },
    { "WriteReplaceWarningResponse",                DNT_UINT32, 0 },
    { "ENBDirectInformationTransfer",               DNT_UINT32, 0 },
    { "Inter-SystemInformationTransferType",        DNT_UINT32, 0 },
    { "MMEDirectInformationTransfer",               DNT_UINT32, 0 },
    { "ENBConfigurationTransfer",                   DNT_UINT32, 0 },
    { "MMEConfigurationTransfer",                   DNT_UINT32, 0 },
    { "PrivateMessage",                             DNT_UINT32, 0 },
    { "KillRequest",                                DNT_UINT32, 0 },
    { "KillResponse",                               DNT_UINT32, 0 },
    { "DownlinkUEAssociatedLPPaTransport",          DNT_UINT32, 0 },
    { "UplinkUEAssociatedLPPaTransport",            DNT_UINT32, 0 },
    { "DownlinkNonUEAssociatedLPPaTransport",       DNT_UINT32, 0 },
    { "UplinkNonUEAssociatedLPPaTransport",         DNT_UINT32, 0 },
    { "S1AP-PDU",                                   DNT_UINT32, 0 },
    { "SONtransferApplicationIdentity",             DNT_UINT32, 0 },
    { "SONtransferRequestContainer",                DNT_UINT32, 0 },
    { "SONtransferResponseContainer",               DNT_UINT32, 0 },
    { "SONtransferCause",                           DNT_UINT32, 0 },
    { "local",                                      DNT_UINT32, 0 },
    { "global",                                     DNT_UINT32, 0 },
    { "ProtocolIE-Field",                           DNT_UINT32, 0 },
    { "id",                                         DNT_UINT32, 0 },
    { "criticality",                                DNT_UINT32, 0 },
    { "value",                                      DNT_UINT32, 0 },
    { "ProtocolIE-SingleContainer",                 DNT_UINT32, 0 },
    { "ProtocolExtensionField",                     DNT_UINT32, 0 },
    { "id",                                         DNT_UINT32, 0 },
    { "extensionValue",                             DNT_UINT32, 0 },
    { "PrivateIE-Field",                            DNT_UINT32, 0 },
    { "id",                                         DNT_UINT32, 0 },
    { "value",                                      DNT_UINT32, 0 },
    { "cellBased",                                  DNT_UINT32, 0 },
    { "tABased",                                    DNT_UINT32, 0 },
    { "pLMNWide",                                   DNT_UINT32, 0 },
    { "priorityLevel",                              DNT_UINT32, 0 },
    { "pre-emptionCapability",                      DNT_UINT32, 0 },
    { "pre-emptionVulnerability",                   DNT_UINT32, 0 },
    { "iE-Extensions",                              DNT_UINT32, 0 },
    { "ProtocolIE-SingleContainer",                 DNT_UINT32, 0 },
    { "e-RAB-ID",                                   DNT_UINT32, 0 },
    { "uL-COUNTvalue",                              DNT_UINT32, 0 },
    { "dL-COUNTvalue",                              DNT_UINT32, 0 },
    { "receiveStatusofULPDCPSDUs",                  DNT_UINT32, 0 },
    { "PLMNidentity",                               DNT_UINT32, 0 },
    { "cellID-Cancelled",                           DNT_UINT32, 0 },
    { "tAI-Cancelled",                              DNT_UINT32, 0 },
    { "emergencyAreaID-Cancelled",                  DNT_UINT32, 0 },
    { "cellID-Broadcast",                           DNT_UINT32, 0 },
    { "tAI-Broadcast",                              DNT_UINT32, 0 },
    { "emergencyAreaID-Broadcast",                  DNT_UINT32, 0 },
    { "CancelledCellinEAI-Item",                    DNT_UINT32, 0 },
    { "eCGI",                                       DNT_UINT32, 0 },
    { "numberOfBroadcasts",                         DNT_UINT32, 0 },
    { "CancelledCellinTAI-Item",                    DNT_UINT32, 0 },
    { "radioNetwork",                               DNT_UINT32, 0 },
    { "transport",                                  DNT_UINT32, 0 },
    { "nas",                                        DNT_UINT32, 0 },
    { "protocol",                                   DNT_UINT32, 0 },
    { "misc",                                       DNT_UINT32, 0 },
    { "CellID-Broadcast-Item",                      DNT_UINT32, 0 },
    { "CellID-Cancelled-Item",                      DNT_UINT32, 0 },
    { "cellIdListforMDT",                           DNT_UINT32, 0 },
    { "EUTRAN-CGI",                                 DNT_UINT32, 0 },
    { "cdma2000OneXMEID",                           DNT_UINT32, 0 },
    { "cdma2000OneXMSI",                            DNT_UINT32, 0 },
    { "cdma2000OneXPilot",                          DNT_UINT32, 0 },
    { "cell-Size",                                  DNT_UINT32, 0 },
    { "pLMNidentity",                               DNT_UINT32, 0 },
    { "lAC",                                        DNT_UINT32, 0 },
    { "cI",                                         DNT_UINT32, 0 },
    { "rAC",                                        DNT_UINT32, 0 },
    { "CSG-IdList-Item",                            DNT_UINT32, 0 },
    { "cSG-Id",                                     DNT_UINT32, 0 },
    { "pDCP-SN",                                    DNT_UINT32, 0 },
    { "hFN",                                        DNT_UINT32, 0 },
    { "procedureCode",                              DNT_UINT32, 0 },
    { "triggeringMessage",                          DNT_UINT32, 0 },
    { "procedureCriticality",                       DNT_UINT32, 0 },
    { "iEsCriticalityDiagnostics",                  DNT_UINT32, 0 },
    { "CriticalityDiagnostics-IE-Item",             DNT_UINT32, 0 },
    { "iECriticality",                              DNT_UINT32, 0 },
    { "iE-ID",                                      DNT_UINT32, 0 },
    { "typeOfError",                                DNT_UINT32, 0 },
    { "EUTRAN-CGI",                                 DNT_UINT32, 0 },
    { "EmergencyAreaID",                            DNT_UINT32, 0 },
    { "EmergencyAreaID-Broadcast-Item",             DNT_UINT32, 0 },
    { "emergencyAreaID",                            DNT_UINT32, 0 },
    { "completedCellinEAI",                         DNT_UINT32, 0 },
    { "EmergencyAreaID-Cancelled-Item",             DNT_UINT32, 0 },
    { "cancelledCellinEAI",                         DNT_UINT32, 0 },
    { "CompletedCellinEAI-Item",                    DNT_UINT32, 0 },
    { "macroENB-ID",                                DNT_UINT32, 0 },
    { "homeENB-ID",                                 DNT_UINT32, 0 },
    { "lAI",                                        DNT_UINT32, 0 },
    { "eNB-ID",                                     DNT_UINT32, 0 },
    { "GUMMEI",                                     DNT_UINT32, 0 },
    { "bearers-SubjectToStatusTransferList",        DNT_UINT32, 0 },
    { "TransportLayerAddress",                      DNT_UINT32, 0 },
    { "PLMNidentity",                               DNT_UINT32, 0 },
    { "ProtocolIE-SingleContainer",                 DNT_UINT32, 0 },
    { "dL-Forwarding",                              DNT_UINT32, 0 },
    { "ProtocolIE-SingleContainer",                 DNT_UINT32, 0 },
    { "cause",                                      DNT_UINT32, 0 },
    { "qCI",                                        DNT_UINT32, 0 },
    { "allocationRetentionPriority",                DNT_UINT32, 0 },
    { "gbrQosInformation",                          DNT_UINT32, 0 },
    { "cell-ID",                                    DNT_UINT32, 0 },
    { "ForbiddenTAs-Item",                          DNT_UINT32, 0 },
    { "pLMN-Identity",                              DNT_UINT32, 0 },
    { "forbiddenTACs",                              DNT_UINT32, 0 },
    { "TAC",                                        DNT_UINT32, 0 },
    { "ForbiddenLAs-Item",                          DNT_UINT32, 0 },
    { "forbiddenLACs",                              DNT_UINT32, 0 },
    { "LAC",                                        DNT_UINT32, 0 },
    { "e-RAB-MaximumBitrateDL",                     DNT_UINT32, 0 },
    { "e-RAB-MaximumBitrateUL",                     DNT_UINT32, 0 },
    { "e-RAB-GuaranteedBitrateDL",                  DNT_UINT32, 0 },
    { "e-RAB-GuaranteedBitrateUL",                  DNT_UINT32, 0 },
    { "mME-Group-ID",                               DNT_UINT32, 0 },
    { "mME-Code",                                   DNT_UINT32, 0 },
    { "servingPLMN",                                DNT_UINT32, 0 },
    { "equivalentPLMNs",                            DNT_UINT32, 0 },
    { "forbiddenTAs",                               DNT_UINT32, 0 },
    { "forbiddenLAs",                               DNT_UINT32, 0 },
    { "forbiddenInterRATs",                         DNT_UINT32, 0 },
    { "measurementsToActivate",                     DNT_UINT32, 0 },
    { "reportingTriggerMDT",                        DNT_UINT32, 0 },
    { "thresholdeventA2",                           DNT_UINT32, 0 },
    { "periodicReportingMDT",                       DNT_UINT32, 0 },
    { "e-UTRAN-Cell",                               DNT_UINT32, 0 },
    { "uTRAN-Cell",                                 DNT_UINT32, 0 },
    { "gERAN-Cell",                                 DNT_UINT32, 0 },
    { "global-Cell-ID",                             DNT_UINT32, 0 },
    { "cellType",                                   DNT_UINT32, 0 },
    { "time-UE-StayedInCell",                       DNT_UINT32, 0 },
    { "undefined",                                  DNT_UINT32, 0 },
    { "loggingInterval",                            DNT_UINT32, 0 },
    { "loggingDuration",                            DNT_UINT32, 0 },
    { "mdt-Activation",                             DNT_UINT32, 0 },
    { "areaScopeOfMDT",                             DNT_UINT32, 0 },
    { "mDTMode",                                    DNT_UINT32, 0 },
    { "immediateMDT",                               DNT_UINT32, 0 },
    { "loggedMDT",                                  DNT_UINT32, 0 },
    { "threshold-RSRP",                             DNT_UINT32, 0 },
    { "threshold-RSRQ",                             DNT_UINT32, 0 },
    { "overloadAction",                             DNT_UINT32, 0 },
    { "reportInterval",                             DNT_UINT32, 0 },
    { "reportAmount",                               DNT_UINT32, 0 },
    { "eventType",                                  DNT_UINT32, 0 },
    { "reportArea",                                 DNT_UINT32, 0 },
    { "rIMInformation",                             DNT_UINT32, 0 },
    { "rIMRoutingAddress",                          DNT_UINT32, 0 },
    { "gERAN-Cell-ID",                              DNT_UINT32, 0 },
    { "targetRNC-ID",                               DNT_UINT32, 0 },
    { "nextHopChainingCount",                       DNT_UINT32, 0 },
    { "nextHopParameter",                           DNT_UINT32, 0 },
    { "sONInformationRequest",                      DNT_UINT32, 0 },
    { "sONInformationReply",                        DNT_UINT32, 0 },
    { "x2TNLConfigurationInfo",                     DNT_UINT32, 0 },
    { "targeteNB-ID",                               DNT_UINT32, 0 },
    { "sourceeNB-ID",                               DNT_UINT32, 0 },
    { "sONInformation",                             DNT_UINT32, 0 },
    { "global-ENB-ID",                              DNT_UINT32, 0 },
    { "selected-TAI",                               DNT_UINT32, 0 },
    { "rRC-Container",                              DNT_UINT32, 0 },
    { "e-RABInformationList",                       DNT_UINT32, 0 },
    { "targetCell-ID",                              DNT_UINT32, 0 },
    { "subscriberProfileIDforRFP",                  DNT_UINT32, 0 },
    { "uE-HistoryInformation",                      DNT_UINT32, 0 },
    { "ServedGUMMEIsItem",                          DNT_UINT32, 0 },
    { "servedPLMNs",                                DNT_UINT32, 0 },
    { "servedGroupIDs",                             DNT_UINT32, 0 },
    { "servedMMECs",                                DNT_UINT32, 0 },
    { "MME-Group-ID",                               DNT_UINT32, 0 },
    { "MME-Code",                                   DNT_UINT32, 0 },
    { "PLMNidentity",                               DNT_UINT32, 0 },
    { "SupportedTAs-Item",                          DNT_UINT32, 0 },
    { "tAC",                                        DNT_UINT32, 0 },
    { "broadcastPLMNs",                             DNT_UINT32, 0 },
    { "stratumLevel",                               DNT_UINT32, 0 },
    { "synchronizationStatus",                      DNT_UINT32, 0 },
    { "mMEC",                                       DNT_UINT32, 0 },
    { "m-TMSI",                                     DNT_UINT32, 0 },
    { "TAI",                                        DNT_UINT32, 0 },
    { "TAI-Broadcast-Item",                         DNT_UINT32, 0 },
    { "tAI",                                        DNT_UINT32, 0 },
    { "completedCellinTAI",                         DNT_UINT32, 0 },
    { "TAI-Cancelled-Item",                         DNT_UINT32, 0 },
    { "cancelledCellinTAI",                         DNT_UINT32, 0 },
    { "tAListforMDT",                               DNT_UINT32, 0 },
    { "TAC",                                        DNT_UINT32, 0 },
    { "CompletedCellinTAI-Item",                    DNT_UINT32, 0 },
    { "cGI",                                        DNT_UINT32, 0 },
    { "rNC-ID",                                     DNT_UINT32, 0 },
    { "extendedRNC-ID",                             DNT_UINT32, 0 },
    { "measurementThreshold",                       DNT_UINT32, 0 },
    { "e-UTRAN-Trace-ID",                           DNT_UINT32, 0 },
    { "interfacesToTrace",                          DNT_UINT32, 0 },
    { "traceDepth",                                 DNT_UINT32, 0 },
    { "traceCollectionEntityIPAddress",             DNT_UINT32, 0 },
    { "uEaggregateMaximumBitRateDL",                DNT_UINT32, 0 },
    { "uEaggregateMaximumBitRateUL",                DNT_UINT32, 0 },
    { "uE-S1AP-ID-pair",                            DNT_UINT32, 0 },
    { "mME-UE-S1AP-ID",                             DNT_UINT32, 0 },
    { "eNB-UE-S1AP-ID",                             DNT_UINT32, 0 },
    { "LastVisitedCell-Item",                       DNT_UINT32, 0 },
    { "s-TMSI",                                     DNT_UINT32, 0 },
    { "iMSI",                                       DNT_UINT32, 0 },
    { "encryptionAlgorithms",                       DNT_UINT32, 0 },
    { "integrityProtectionAlgorithms",              DNT_UINT32, 0 },
    { "cellIDList",                                 DNT_UINT32, 0 },
    { "trackingAreaListforWarning",                 DNT_UINT32, 0 },
    { "emergencyAreaIDList",                        DNT_UINT32, 0 },
    { "eNBX2TransportLayerAddresses",               DNT_UINT32, 0 },
    { "ENBX2ExtTLA",                                DNT_UINT32, 0 },
    { "iPsecTLA",                                   DNT_UINT32, 0 },
    { "gTPTLAa",                                    DNT_UINT32, 0 },
    { "TransportLayerAddress",                      DNT_UINT32, 0 },
    { "protocolIEs",                                DNT_UINT32, 0 },
    { "dL-transportLayerAddress",                   DNT_UINT32, 0 },
    { "dL-gTP-TEID",                                DNT_UINT32, 0 },
    { "uL-TransportLayerAddress",                   DNT_UINT32, 0 },
    { "uL-GTP-TEID",                                DNT_UINT32, 0 },
    { "transportLayerAddress",                      DNT_UINT32, 0 },
    { "gTP-TEID",                                   DNT_UINT32, 0 },
    { "e-RABlevelQosParameters",                    DNT_UINT32, 0 },
    { "ProtocolIE-SingleContainer",                 DNT_UINT32, 0 },
    { "e-RABlevelQoSParameters",                    DNT_UINT32, 0 },
    { "nAS-PDU",                                    DNT_UINT32, 0 },
    { "ProtocolIE-SingleContainer",                 DNT_UINT32, 0 },
    { "ProtocolIE-SingleContainer",                 DNT_UINT32, 0 },
    { "e-RABLevelQoSParameters",                    DNT_UINT32, 0 },
    { "ProtocolIE-SingleContainer",                 DNT_UINT32, 0 },
    { "ProtocolIE-SingleContainer",                 DNT_UINT32, 0 },
    { "ProtocolIE-SingleContainer",                 DNT_UINT32, 0 },
    { "ProtocolIE-SingleContainer",                 DNT_UINT32, 0 },
    { "ProtocolIE-SingleContainer",                 DNT_UINT32, 0 },
    { "s1-Interface",                               DNT_UINT32, 0 },
    { "partOfS1-Interface",                         DNT_UINT32, 0 },
    { "ProtocolIE-SingleContainer",                 DNT_UINT32, 0 },
    { "ProtocolIE-SingleContainer",                 DNT_UINT32, 0 },
    { "rIMTransfer",                                DNT_UINT32, 0 },
    { "privateIEs",                                 DNT_UINT32, 0 },
    { "initiatingMessage",                          DNT_UINT32, 0 },
    { "successfulOutcome",                          DNT_UINT32, 0 },
    { "unsuccessfulOutcome",                        DNT_UINT32, 0 },
    { "value",                                      DNT_UINT32, 0 },
    { "cellLoadReporting",                          DNT_UINT32, 0 },
    { "multiCellLoadReporting",                     DNT_UINT32, 0 },
    { "eventTriggeredCellLoadReporting",            DNT_UINT32, 0 },
    { "hOReporting",                                DNT_UINT32, 0 },
    { "cellLoadReporting",                          DNT_UINT32, 0 },
    { "multiCellLoadReporting",                     DNT_UINT32, 0 },
    { "eventTriggeredCellLoadReporting",            DNT_UINT32, 0 },
    { "hOReporting",                                DNT_UINT32, 0 },
    { "cellLoadReporting",                          DNT_UINT32, 0 },
    { "multiCellLoadReporting",                     DNT_UINT32, 0 },
    { "eventTriggeredCellLoadReporting",            DNT_UINT32, 0 },
    { "hOReporting",                                DNT_UINT32, 0 },
    { "eUTRAN",                                     DNT_UINT32, 0 },
    { "uTRAN",                                      DNT_UINT32, 0 },
    { "gERAN",                                      DNT_UINT32, 0 },
    { "compositeAvailableCapacityGroup",            DNT_UINT32, 0 },
    { "eUTRAN",                                     DNT_UINT32, 0 },
    { "IRAT-Cell-ID",                               DNT_UINT32, 0 },
    { "requestedCellList",                          DNT_UINT32, 0 },
    { "cell-ID",                                    DNT_UINT32, 0 },
    { "ReportingCellList-Item",                     DNT_UINT32, 0 },
    { "reportingCellList",                          DNT_UINT32, 0 },
    { "cellLoadReportingResponse",                  DNT_UINT32, 0 },
    { "numberOfMeasurementReportingLevels",         DNT_UINT32, 0 },
    { "overloadFlag",                               DNT_UINT32, 0 },
    { "hoType",                                     DNT_UINT32, 0 },
    { "hoReportType",                               DNT_UINT32, 0 },
    { "hosourceID",                                 DNT_UINT32, 0 },
    { "hoTargetID",                                 DNT_UINT32, 0 },
    { "candidateCellList",                          DNT_UINT32, 0 },
    { "IRAT-Cell-ID",                               DNT_UINT32, 0 }
};

s1ap_pie_t s1ap_pies[] = {
    {  0, "MME-UE-S1AP-ID",                  pie_0_MME_UE_ID },
    {  1, "HandoverType",                    pie_1_HandoverType },
    {  2, "Cause",                           pie_2_Cause },
    {  3, "SourceID",                        pie_3_SourceID },
    {  4, "TargetID",                        pie_4_TargetID },
    {  5, NULL,                              NULL },
    {  6, NULL,                              NULL },
    {  7, NULL,                              NULL },
    {  8, "ENB-UE-S1AP-ID",                  pie_8_ENB_UE_ID },
    {  9, NULL,                              NULL },
    { 10, NULL,                              NULL },
    { 11, NULL,                              NULL },
    { 12, "E-RABSubjecttoDataForwardingList",pie_12_ERABSubjecttoDataForwardingList },
    { 13, "E-RABtoReleaseListHOCmd",         pie_13_ERABtoReleaseListHOCmd },
    { 14, "E-RABDataForwardingItem",         pie_14_ERABDataForwardingItem },
    { 15, "E-RABReleaseItemBearerRelComp",   pie_15_ERABReleaseItemBearerRelComp },
    { 16, "E-RABToBeSetupListBearerSUReq",   pie_16_ERABToBeSetupListBearerSUReq },
    { 17, "E-RABToBeSetupItemBearerSUReq",   pie_17_ERABToBeSetupItemBearerSUReq },
    { 18, "E-RABAdmittedList",               pie_18_ERABAdmittedList },
    { 19, "E-RABFailedToSetupListHOReqAck",  pie_19_ERABFailedToSetupListHOReqAck },
    { 20, "RABAdmittedItem",                 pie_20_RABAdmittedItem },
    { 21, "E-RABFailedtoSetupItemHOReqAck",  pie_21_ERABFailedtoSetupItemHOReqAck },
    { 22, "E-RABToBeSwitchedDLList",         pie_22_ERABToBeSwitchedDLList },
    { 23, "E-RABToBeSwitchedDLItem",         pie_23_ERABToBeSwitchedDLItem },
    { 24, "E-RABToBeSetupListCtxtSUReq",     pie_24_ERABToBeSetupListCtxtSUReq },
    { 25, "TraceActivation",                 pie_25_TraceActivation },
    { 26, "NAS-PDU",                         pie_26_NAS_PDU },
    { 27, "E-RABToBeSetupItemHOReq",         pie_27_ERABToBeSetupItemHOReq },
    { 28, "E-RABSetupListBearerSURes",       pie_28_ERABSetupListBearerSURes },
    { 29, "E-RABFailedToSetupListBearerSURes", pie_29_ERABFailedToSetupListBearerSURes },
    { 30, "E-RABToBeModifiedListBearerModReq", pie_30_ERABToBeModifiedListBearerModReq },
    { 31, "E-RABModifyListBearerModRes",     pie_31_ERABModifyListBearerModRes },
    { 32, "E-RABFailedToModifyList",         pie_32_ERABFailedToModifyList },
    { 33, "E-RABToBeReleasedList",           pie_33_ERABToBeReleasedList },
    { 34, "E-RABFailedToReleaseList",        pie_34_ERABFailedToReleaseList },
    { 35, "E-RABItem",                       pie_35_ERABItem },
    { 36, "E-RABToBeModifiedItemBearerModReq", pie_36_ERABToBeModifiedItemBearerModReq },
    { 37, "E-RABModifyItemBearerModRes",     pie_37_ERABModifyItemBearerModRes },
    { 38, "E-RABReleaseItem",                pie_38_ERABReleaseItem },
    { 39, "E-RABSetupItemBearerSURes",       pie_39_ERABSetupItemBearerSURes },


    { 40, "SecurityContext",                 pie_40_SecurityContext },
    { 41, "HandoverRestrictionList",         pie_41_HandoverRestrictionList },
    { 42, NULL,                              NULL },
    { 43, "UEPagingID",                      pie_43_UEPagingID },
    { 44, "pagingDRX",                       pie_44_pagingDRX },
    { 45, NULL,                              NULL },
    { 46, "TAIList",                         pie_46_TAIList },
    { 47, "TAIItem",                         pie_47_TAIItem },
    { 48, "E-RABFailedToSetupListCtxtSURes", pie_48_ERABFailedToSetupListCtxtSURes },
    { 49, "E-RABReleaseItemHOCmd",           pie_49_ERABReleaseItemHOCmd },
    { 50, "E-RABSetupItemCtxtSURes",         pie_50_ERABSetupItemCtxtSURes },
    { 51, "E-RABSetupListCtxtSURes",         pie_51_ERABSetupListCtxtSURes },
    { 52, "E-RABToBeSetupItemCtxtSUReq",     pie_52_ERABToBeSetupItemCtxtSUReq },
    { 53, "E-RABToBeSetupListHOReq",         pie_53_ERABToBeSetupListHOReq },
    { 54, NULL,                              NULL },
    { 55, "GERANtoLTEHOInformationRes",      pie_55_GERANtoLTEHOInformationRes },
    { 56, NULL,                              NULL },
    { 57, "E-RABSubjecttoDataForwardingList",pie_57_UTRANtoLTEHOInformationRes },
    { 58, "UTRANtoLTEHOInformationRes",      pie_58_CriticalityDiagnostics },
    { 59, "Global_ENB_ID",                   pie_59_Global_ENB_ID },
    { 60, "eNBname",                         pie_60_eNBname },
    { 61, "MMEname",                         pie_61_MMEname },
    { 62, NULL,                              NULL },
    { 63, "ServedPLMNs",                     pie_63_ServedPLMNs },
    { 64, "SupportedTAs",                    pie_64_SupportedTAs },
    { 65, "TimeToWait",                      pie_65_TimeToWait },
    { 66, "UEAggregateMaximumBitrate",       pie_66_UEAggregateMaximumBitrate },
    { 67, "TAI",                             pie_67_TAI },
    { 68, NULL,                              NULL },
    { 69, "E-RABReleaseListBearerRelComp",   pie_69_ERABReleaseListBearerRelComp },
    { 70, "cdma2000PDU",                     pie_70_cdma2000PDU },
    { 71, "cdma2000RATType",                 pie_71_cdma2000RATType },
    { 72, "cdma2000SectorID",                pie_72_cdma2000SectorID },
    { 73, "SecurityKey",                     pie_73_SecurityKey },
    { 74, "UERadioCapability",               pie_74_UERadioCapability },
    { 75, "GUMMEI_ID",                       pie_75_GUMMEI_ID },
    { 76, NULL,                              NULL },
    { 77, NULL,                              NULL },
    { 78, "E-RABInformationListItem",        pie_78_ERABInformationListItem },
    { 79, "DirectForwardingPathAvailability",pie_79_DirectForwardingPathAvailability },


    {  80, "UEIdentityIndexValue",            pie_80_UEIdentityIndexValue },
    {  81, NULL,                              NULL },
    {  82, NULL,                              NULL },
    {  83, "cdma2000HOStatus",                pie_83_cdma2000HOStatus },
    {  84, "cdma2000HORequiredIndication",    pie_84_cdma2000HORequiredIndication },
    {  85, NULL,                              NULL },
    {  86, "EUTRANTraceID",                   pie_86_EUTRANTraceID },
    {  87, "RelativeMMECapacity",             pie_87_RelativeMMECapacity },
    {  88, "SourceMME_UE_S1AP_ID",            pie_88_SourceMME_UE_S1AP_ID },
    {  89, "BearersSubjectToStatusTransferItem",         pie_89_BearersSubjectToStatusTransferItem },
    {  90, "eNB_StatusTransferTransparentContainer",     pie_90_eNB_StatusTransferTransparentContainer },
    {  91, "UE-associatedLogicalS1ConnectionItem",       pie_91_UE_associatedLogicalS1ConnectionItem },
    {  92, "ResetType",                                  pie_92_ResetType },
    {  93, "UE-associatedLogicalS1ConnectionListResAck", pie_93_UE_associatedLogicalS1ConnectionListResAck },
    {  94, "E-RABToBeSwitchedULItem",         pie_94_ERABToBeSwitchedULItem },
    {  95, "E-RABToBeSwitchedULList",         pie_95_ERABToBeSwitchedULList },
    {  96, "STMSI",                           pie_96_STMSI },
    {  97, "cdma2000OneXRAND",                pie_97_cdma2000OneXRAND },
    {  98, "RequestType",                     pie_98_RequestType },
    {  99, "UE-S1AP-IDs",                     pie_99_UE_S1AP_IDs },
    { 100, "EUTRAN-CGI",                      pie_100_EUTRAN_CGI },
    { 101, "OverloadResponse",                pie_101_OverloadResponse },
    { 102, "cdma2000OneXSRVCCInfo",           pie_102_cdma2000OneXSRVCCInfo },
    { 103, "E-RABFailedToBeReleasedList",     pie_103_ERABFailedToBeReleasedList },
    { 104, "SourceToTargetTransparentContainer", pie_104_SourceToTargetTransparentContainer },
    { 105, "ServedGUMMEIs",                   pie_105_ServedGUMMEIs },
    { 106, "SubscriberProfileIDforRFP",       pie_106_SubscriberProfileIDforRFP },
    { 107, "UESecurityCapabilities",          pie_107_UESecurityCapabilities },
    { 108, "CSFallbackIndicator",             pie_108_CSFallbackIndicator },
    { 109, "CNDomain",                        pie_109_CNDomain },
    { 110, "E-RABReleasedList",               pie_110_ERABReleasedList },
    { 111, "MessageIdentifier",               pie_111_MessageIdentifier },
    { 112, "SerialNumber",                    pie_112_SerialNumber },
    { 113, "WarningAreaList",                 pie_113_WarningAreaList },
    { 114, "RepetitionPeriod",                pie_114_RepetitionPeriod },
    { 115, "NumberofBroadcastRequest",        pie_115_NumberofBroadcastRequest },
    { 116, "WarningType",                     pie_116_WarningType },
    { 117, "WarningSecurityInfo",             pie_117_WarningSecurityInfo },
    { 118, "DataCodingScheme",                pie_118_DataCodingScheme },
    { 119, "WarningMessageContents",          pie_119_WarningMessageContents },


    { 120, "BroadcastCompletedAreaList",            pie_120_BroadcastCompletedAreaList },
    { 121, "InterSystemInformationTransferTypeEDT", pie_121_InterSystemInformationTransferTypeEDT },
    { 122, "InterSystemInformationTransferTypeMDT", pie_122_InterSystemInformationTransferTypeMDT },
    { 123, "TargetToSourceTransparentContainer",    pie_123_TargetToSourceTransparentContainer },
    { 124, "SRVCCOperationPossible",          pie_124_SRVCCOperationPossible },
    { 125, "SRVCCHOIndication",               pie_125_SRVCCHOIndication },
    { 126, "NASDownlinkCount",                pie_126_NASDownlinkCount },
    { 127, "CSGId",                           pie_127_CSGId },
    { 128, "CSGIdList",                       pie_128_CSGIdList },
    { 129, "SONConfigurationTransferECT",     pie_129_SONConfigurationTransferECT },
    { 130, "SONConfigurationTransferMCT",     pie_130_SONConfigurationTransferMCT },
    { 131, "TraceCollectionEntityIPAddress",  pie_131_TraceCollectionEntityIPAddress },
    { 132, "MSClassmark2",                    pie_132_MSClassmark2 },
    { 133, "MSClassmark3",                    pie_133_MSClassmark3 },
    { 134, "RRCEstablishmentCause",           pie_134_RRCEstablishmentCause },
    { 135, "NASSecurityParametersFromEUTRAN", pie_135_NASSecurityParametersFromEUTRAN },
    { 136, "NASSecurityParametersToEUTRAN",   pie_136_NASSecurityParametersToEUTRAN },
    { 137, "DefaultPagingDRX",                pie_137_DefaultPagingDRX },
    { 138, "SourceToTargetTransparentContainerSecondary", pie_138_SourceToTargetTransparentContainerSecondary },
    { 139, "TargetToSourceTransparentContainerSecondary", pie_139_TargetToSourceTransparentContainerSecondary },
    { 140, "EUTRANRoundTripDelayEstimationInfo", pie_140_EUTRANRoundTripDelayEstimationInfo },
    { 141, "BroadcastCancelledAreaList",         pie_141_BroadcastCancelledAreaList },
    { 142, "ConcurrentWarningMessageIndicator",  pie_142_ConcurrentWarningMessageIndicator },
    { 143, "DataForwardingNotPossible",       pie_143_DataForwardingNotPossible },
    { 144, "ExtendedRepetitionPeriod",        pie_144_ExtendedRepetitionPeriod },
    { 145, "CellAccessMode",                  pie_145_CellAccessMode },
    { 146, "CSGMembershipStatus",             pie_146_CSGMembershipStatus },
    { 147, "LPPaPDU",                         pie_147_LPPaPDU },
    { 148, "RoutingID",                       pie_148_RoutingID },
    { 149, "TimeSynchronizationInfo",         pie_149_TimeSynchronizationInfo },
    { 150, "PSServiceNotAvailable",           pie_150_PSServiceNotAvailable },
    { 151, "PagingPriority",                  pie_151_PagingPriority },
    { 152, "x2TNLConfigurationInfo",          pie_152_x2TNLConfigurationInfo },
    { 153, "eNBX2ExtendedTransportLayerAddresses", pie_153_eNBX2ExtendedTransportLayerAddresses },
    { 154, "E-RABGUMMEIList",                 pie_154_GUMMEIList },
    { 155, "GWTransportLayerAddress",         pie_155_GWTransportLayerAddress },
    { 156, "CorrelationID",                   pie_156_CorrelationID },
    { 157, "SourceMME_GUMMEI",                pie_157_SourceMME_GUMMEI },
    { 158, "MME-UE-S1AP-ID-2",                pie_158_MME_UE_S1AP_ID_2 },
    { 159, "RegisteredLAI",                   pie_159_RegisteredLAI },


    { 160, "RelayNode-Indicator",             pie_160_RelayNode_Indicator },
    { 161, "TrafficLoadReductionIndication",  pie_161_TrafficLoadReductionIndication },
    { 162, "MDTConfiguration",                pie_162_MDTConfiguration },
    { 163, "MMERelaySupportIndicator",        pie_163_MMERelaySupportIndicator },
    { 164, "GWContextReleaseIndication",      pie_164_GWContextReleaseIndication },
    { 165, "ManagementBasedMDTAllowed",       pie_165_ManagementBasedMDTAllowed },
};
const size_t s1ap_pies_sz = sizeof(s1ap_pies) / sizeof(s1ap_pies[0]);

s1ap_proccode_t s1ap_proccodes[] = {
    { 0, "HandoverPreparation"},
    { 1, "HandoverResourceAllocation"},
    { 2, "HandoverNotification"},
    { 3, "PathSwitchRequest"},
    { 4, "HandoverCancel"},
    { 5, "E-RABSetup"},
    { 6, "E-RABModify"},
    { 7, "E-RABRelease"},
    { 8, "E-RABReleaseIndication"},
    { 9, "InitialContextSetup"},
    {10, "Paging"},
    {11, "downlinkNASTransport"},
    {12, "initialUEMessage"},
    {13, "uplinkNASTransport"},
    {14, "Reset"},
    {15, "ErrorIndication"},
    {16, "NASNonDeliveryIndication"},
    {17, "S1Setup"},
    {18, "UEContextReleaseRequest"},
    {19, "DownlinkS1cdma2000tunneling"},
    {20, "UplinkS1cdma2000tunneling"},
    {21, "UEContextModification"},
    {22, "UECapabilityInfoIndication"},
    {23, "UEContextRelease"},
    {24, "eNBStatusTransfer"},
    {25, "MMEStatusTransfer"},
    {26, "DeactivateTrace"},
    {27, "TraceStart"},
    {28, "TraceFailureIndication"},
    {29, "ENBConfigurationUpdate"},
    {30, "MMEConfigurationUpdate"},
    {31, "LocationReportingControl"},
    {32, "LocationReportingFailureIndication"},
    {33, "LocationReport"},
    {34, "OverloadStart"},
    {35, "OverloadStop"},
    {36, "WriteReplaceWarning"},
    {37, "eNBDirectInformationTransfer"},
    {38, "MMEDirectInformationTransfer"},
    {39, "PrivateMessage"},
    {40, "eNBConfigurationTransfer"},
    {41, "MMEConfigurationTransfer"},
    {42, "CellTrafficTrace"},
    {43, "Kill"},
    {44, "downlinkUEAssociatedLPPaTransport"},
    {45, "uplinkUEAssociatedLPPaTransport"},
    {46, "downlinkNonUEAssociatedLPPaTransport"},
    {47, "uplinkNonUEAssociatedLPPaTransport"}
};
const size_t s1ap_proccodes_sz = sizeof(s1ap_proccodes) / sizeof(s1ap_proccodes[0]);
